-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sha256_acc_sha256_acc_Pipeline_VITIS_LOOP_15_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_stream_TVALID : IN STD_LOGIC;
    in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_stream_TREADY : OUT STD_LOGIC;
    w_V_15_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    w_V_15_out_ap_vld : OUT STD_LOGIC;
    w_V_14_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    w_V_14_out_ap_vld : OUT STD_LOGIC;
    w_V_13_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    w_V_13_out_ap_vld : OUT STD_LOGIC;
    w_V_12_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    w_V_12_out_ap_vld : OUT STD_LOGIC;
    w_V_11_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    w_V_11_out_ap_vld : OUT STD_LOGIC;
    w_V_10_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    w_V_10_out_ap_vld : OUT STD_LOGIC;
    w_V_9_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    w_V_9_out_ap_vld : OUT STD_LOGIC;
    w_V_8_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    w_V_8_out_ap_vld : OUT STD_LOGIC;
    w_V_7_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    w_V_7_out_ap_vld : OUT STD_LOGIC;
    w_V_6_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    w_V_6_out_ap_vld : OUT STD_LOGIC;
    w_V_5_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    w_V_5_out_ap_vld : OUT STD_LOGIC;
    w_V_4_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    w_V_4_out_ap_vld : OUT STD_LOGIC;
    w_V_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    w_V_3_out_ap_vld : OUT STD_LOGIC;
    w_V_2_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    w_V_2_out_ap_vld : OUT STD_LOGIC;
    w_V_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    w_V_1_out_ap_vld : OUT STD_LOGIC;
    w_V_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    w_V_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of sha256_acc_sha256_acc_Pipeline_VITIS_LOOP_15_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal icmp_ln15_fu_292_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal in_stream_TDATA_blk_n : STD_LOGIC;
    signal i_fu_98 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln15_fu_298_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_2 : STD_LOGIC_VECTOR (4 downto 0);
    signal w_V_fu_102 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln17_fu_304_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal w_V_1_fu_106 : STD_LOGIC_VECTOR (31 downto 0);
    signal w_V_2_fu_110 : STD_LOGIC_VECTOR (31 downto 0);
    signal w_V_3_fu_114 : STD_LOGIC_VECTOR (31 downto 0);
    signal w_V_4_fu_118 : STD_LOGIC_VECTOR (31 downto 0);
    signal w_V_5_fu_122 : STD_LOGIC_VECTOR (31 downto 0);
    signal w_V_6_fu_126 : STD_LOGIC_VECTOR (31 downto 0);
    signal w_V_7_fu_130 : STD_LOGIC_VECTOR (31 downto 0);
    signal w_V_8_fu_134 : STD_LOGIC_VECTOR (31 downto 0);
    signal w_V_9_fu_138 : STD_LOGIC_VECTOR (31 downto 0);
    signal w_V_10_fu_142 : STD_LOGIC_VECTOR (31 downto 0);
    signal w_V_11_fu_146 : STD_LOGIC_VECTOR (31 downto 0);
    signal w_V_12_fu_150 : STD_LOGIC_VECTOR (31 downto 0);
    signal w_V_13_fu_154 : STD_LOGIC_VECTOR (31 downto 0);
    signal w_V_14_fu_158 : STD_LOGIC_VECTOR (31 downto 0);
    signal w_V_15_fu_162 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_249 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component sha256_acc_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component sha256_acc_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    i_fu_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_249)) then
                if ((icmp_ln15_fu_292_p2 = ap_const_lv1_0)) then 
                    i_fu_98 <= add_ln15_fu_298_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_98 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (trunc_ln17_fu_304_p1 = ap_const_lv4_A) and (icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                w_V_10_fu_142 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (trunc_ln17_fu_304_p1 = ap_const_lv4_B) and (icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                w_V_11_fu_146 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (trunc_ln17_fu_304_p1 = ap_const_lv4_C) and (icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                w_V_12_fu_150 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (trunc_ln17_fu_304_p1 = ap_const_lv4_D) and (icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                w_V_13_fu_154 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (trunc_ln17_fu_304_p1 = ap_const_lv4_E) and (icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                w_V_14_fu_158 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (trunc_ln17_fu_304_p1 = ap_const_lv4_F) and (icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                w_V_15_fu_162 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (trunc_ln17_fu_304_p1 = ap_const_lv4_1) and (icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                w_V_1_fu_106 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (trunc_ln17_fu_304_p1 = ap_const_lv4_2) and (icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                w_V_2_fu_110 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (trunc_ln17_fu_304_p1 = ap_const_lv4_3) and (icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                w_V_3_fu_114 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (trunc_ln17_fu_304_p1 = ap_const_lv4_4) and (icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                w_V_4_fu_118 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (trunc_ln17_fu_304_p1 = ap_const_lv4_5) and (icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                w_V_5_fu_122 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (trunc_ln17_fu_304_p1 = ap_const_lv4_6) and (icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                w_V_6_fu_126 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (trunc_ln17_fu_304_p1 = ap_const_lv4_7) and (icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                w_V_7_fu_130 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (trunc_ln17_fu_304_p1 = ap_const_lv4_8) and (icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                w_V_8_fu_134 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (trunc_ln17_fu_304_p1 = ap_const_lv4_9) and (icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                w_V_9_fu_138 <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (trunc_ln17_fu_304_p1 = ap_const_lv4_0) and (icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                w_V_fu_102 <= in_stream_TDATA;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, in_stream_TVALID, icmp_ln15_fu_292_p2, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln15_fu_298_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_2) + unsigned(ap_const_lv5_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(in_stream_TVALID, icmp_ln15_fu_292_p2, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) or ((icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(in_stream_TVALID, icmp_ln15_fu_292_p2, ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_start_int = ap_const_logic_0) or ((icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)));
    end process;


    ap_condition_249_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, icmp_ln15_fu_292_p2, ap_start_int)
    begin
                ap_condition_249 <= (not(((ap_start_int = ap_const_logic_0) or ((icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, icmp_ln15_fu_292_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (icmp_ln15_fu_292_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, icmp_ln15_fu_292_p2, ap_loop_exit_ready, ap_done_reg, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, icmp_ln15_fu_292_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_2_assign_proc : process(ap_CS_fsm_state1, i_fu_98, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_i_2 <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_i_2 <= i_fu_98;
        end if; 
    end process;

    icmp_ln15_fu_292_p2 <= "1" when (ap_sig_allocacmp_i_2 = ap_const_lv5_10) else "0";

    in_stream_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, icmp_ln15_fu_292_p2, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            in_stream_TDATA_blk_n <= in_stream_TVALID;
        else 
            in_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in_stream_TREADY_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, icmp_ln15_fu_292_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            in_stream_TREADY <= ap_const_logic_1;
        else 
            in_stream_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln17_fu_304_p1 <= ap_sig_allocacmp_i_2(4 - 1 downto 0);
    w_V_10_out <= w_V_10_fu_142;

    w_V_10_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, icmp_ln15_fu_292_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (icmp_ln15_fu_292_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            w_V_10_out_ap_vld <= ap_const_logic_1;
        else 
            w_V_10_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    w_V_11_out <= w_V_11_fu_146;

    w_V_11_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, icmp_ln15_fu_292_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (icmp_ln15_fu_292_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            w_V_11_out_ap_vld <= ap_const_logic_1;
        else 
            w_V_11_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    w_V_12_out <= w_V_12_fu_150;

    w_V_12_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, icmp_ln15_fu_292_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (icmp_ln15_fu_292_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            w_V_12_out_ap_vld <= ap_const_logic_1;
        else 
            w_V_12_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    w_V_13_out <= w_V_13_fu_154;

    w_V_13_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, icmp_ln15_fu_292_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (icmp_ln15_fu_292_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            w_V_13_out_ap_vld <= ap_const_logic_1;
        else 
            w_V_13_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    w_V_14_out <= w_V_14_fu_158;

    w_V_14_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, icmp_ln15_fu_292_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (icmp_ln15_fu_292_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            w_V_14_out_ap_vld <= ap_const_logic_1;
        else 
            w_V_14_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    w_V_15_out <= w_V_15_fu_162;

    w_V_15_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, icmp_ln15_fu_292_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (icmp_ln15_fu_292_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            w_V_15_out_ap_vld <= ap_const_logic_1;
        else 
            w_V_15_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    w_V_1_out <= w_V_1_fu_106;

    w_V_1_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, icmp_ln15_fu_292_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (icmp_ln15_fu_292_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            w_V_1_out_ap_vld <= ap_const_logic_1;
        else 
            w_V_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    w_V_2_out <= w_V_2_fu_110;

    w_V_2_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, icmp_ln15_fu_292_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (icmp_ln15_fu_292_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            w_V_2_out_ap_vld <= ap_const_logic_1;
        else 
            w_V_2_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    w_V_3_out <= w_V_3_fu_114;

    w_V_3_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, icmp_ln15_fu_292_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (icmp_ln15_fu_292_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            w_V_3_out_ap_vld <= ap_const_logic_1;
        else 
            w_V_3_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    w_V_4_out <= w_V_4_fu_118;

    w_V_4_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, icmp_ln15_fu_292_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (icmp_ln15_fu_292_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            w_V_4_out_ap_vld <= ap_const_logic_1;
        else 
            w_V_4_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    w_V_5_out <= w_V_5_fu_122;

    w_V_5_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, icmp_ln15_fu_292_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (icmp_ln15_fu_292_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            w_V_5_out_ap_vld <= ap_const_logic_1;
        else 
            w_V_5_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    w_V_6_out <= w_V_6_fu_126;

    w_V_6_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, icmp_ln15_fu_292_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (icmp_ln15_fu_292_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            w_V_6_out_ap_vld <= ap_const_logic_1;
        else 
            w_V_6_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    w_V_7_out <= w_V_7_fu_130;

    w_V_7_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, icmp_ln15_fu_292_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (icmp_ln15_fu_292_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            w_V_7_out_ap_vld <= ap_const_logic_1;
        else 
            w_V_7_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    w_V_8_out <= w_V_8_fu_134;

    w_V_8_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, icmp_ln15_fu_292_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (icmp_ln15_fu_292_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            w_V_8_out_ap_vld <= ap_const_logic_1;
        else 
            w_V_8_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    w_V_9_out <= w_V_9_fu_138;

    w_V_9_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, icmp_ln15_fu_292_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (icmp_ln15_fu_292_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            w_V_9_out_ap_vld <= ap_const_logic_1;
        else 
            w_V_9_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    w_V_out <= w_V_fu_102;

    w_V_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, icmp_ln15_fu_292_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln15_fu_292_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (icmp_ln15_fu_292_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            w_V_out_ap_vld <= ap_const_logic_1;
        else 
            w_V_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

end behav;
