// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sha256_acc_sha256_acc_Pipeline_VITIS_LOOP_30_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        w_V_reload,
        w_V_1_reload,
        w_V_2_reload,
        w_V_3_reload,
        w_V_4_reload,
        w_V_5_reload,
        w_V_6_reload,
        w_V_7_reload,
        w_V_8_reload,
        w_V_9_reload,
        w_V_10_reload,
        w_V_11_reload,
        w_V_12_reload,
        w_V_13_reload,
        w_V_14_reload,
        w_V_15_reload,
        w_V_33_reload,
        w_V_34_reload,
        w_V_35_reload,
        w_V_36_reload,
        w_V_37_reload,
        w_V_38_reload,
        w_V_39_reload,
        w_V_40_reload,
        w_V_41_reload,
        w_V_42_reload,
        w_V_43_reload,
        w_V_44_reload,
        w_V_45_reload,
        w_V_46_reload,
        w_V_47_reload,
        w_V_48_reload,
        w_V_49_reload,
        w_V_50_reload,
        w_V_51_reload,
        w_V_52_reload,
        w_V_53_reload,
        w_V_54_reload,
        w_V_55_reload,
        w_V_56_reload,
        w_V_57_reload,
        w_V_58_reload,
        w_V_59_reload,
        w_V_60_reload,
        w_V_61_reload,
        w_V_62_reload,
        w_V_63_reload,
        w_V_64_reload,
        w_V_65_reload,
        w_V_66_reload,
        w_V_67_reload,
        w_V_68_reload,
        w_V_69_reload,
        w_V_70_reload,
        w_V_71_reload,
        w_V_72_reload,
        w_V_73_reload,
        w_V_74_reload,
        w_V_75_reload,
        w_V_76_reload,
        w_V_77_reload,
        w_V_78_reload,
        w_V_79_reload,
        w_V_80_reload,
        h_val_V_out,
        h_val_V_out_ap_vld,
        g_V_out,
        g_V_out_ap_vld,
        f_V_out,
        f_V_out_ap_vld,
        e_V_2_out,
        e_V_2_out_ap_vld,
        d_V_out,
        d_V_out_ap_vld,
        c_V_out,
        c_V_out_ap_vld,
        b_V_out,
        b_V_out_ap_vld,
        a_V_2_out,
        a_V_2_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] w_V_reload;
input  [31:0] w_V_1_reload;
input  [31:0] w_V_2_reload;
input  [31:0] w_V_3_reload;
input  [31:0] w_V_4_reload;
input  [31:0] w_V_5_reload;
input  [31:0] w_V_6_reload;
input  [31:0] w_V_7_reload;
input  [31:0] w_V_8_reload;
input  [31:0] w_V_9_reload;
input  [31:0] w_V_10_reload;
input  [31:0] w_V_11_reload;
input  [31:0] w_V_12_reload;
input  [31:0] w_V_13_reload;
input  [31:0] w_V_14_reload;
input  [31:0] w_V_15_reload;
input  [31:0] w_V_33_reload;
input  [31:0] w_V_34_reload;
input  [31:0] w_V_35_reload;
input  [31:0] w_V_36_reload;
input  [31:0] w_V_37_reload;
input  [31:0] w_V_38_reload;
input  [31:0] w_V_39_reload;
input  [31:0] w_V_40_reload;
input  [31:0] w_V_41_reload;
input  [31:0] w_V_42_reload;
input  [31:0] w_V_43_reload;
input  [31:0] w_V_44_reload;
input  [31:0] w_V_45_reload;
input  [31:0] w_V_46_reload;
input  [31:0] w_V_47_reload;
input  [31:0] w_V_48_reload;
input  [31:0] w_V_49_reload;
input  [31:0] w_V_50_reload;
input  [31:0] w_V_51_reload;
input  [31:0] w_V_52_reload;
input  [31:0] w_V_53_reload;
input  [31:0] w_V_54_reload;
input  [31:0] w_V_55_reload;
input  [31:0] w_V_56_reload;
input  [31:0] w_V_57_reload;
input  [31:0] w_V_58_reload;
input  [31:0] w_V_59_reload;
input  [31:0] w_V_60_reload;
input  [31:0] w_V_61_reload;
input  [31:0] w_V_62_reload;
input  [31:0] w_V_63_reload;
input  [31:0] w_V_64_reload;
input  [31:0] w_V_65_reload;
input  [31:0] w_V_66_reload;
input  [31:0] w_V_67_reload;
input  [31:0] w_V_68_reload;
input  [31:0] w_V_69_reload;
input  [31:0] w_V_70_reload;
input  [31:0] w_V_71_reload;
input  [31:0] w_V_72_reload;
input  [31:0] w_V_73_reload;
input  [31:0] w_V_74_reload;
input  [31:0] w_V_75_reload;
input  [31:0] w_V_76_reload;
input  [31:0] w_V_77_reload;
input  [31:0] w_V_78_reload;
input  [31:0] w_V_79_reload;
input  [31:0] w_V_80_reload;
output  [31:0] h_val_V_out;
output   h_val_V_out_ap_vld;
output  [31:0] g_V_out;
output   g_V_out_ap_vld;
output  [31:0] f_V_out;
output   f_V_out_ap_vld;
output  [31:0] e_V_2_out;
output   e_V_2_out_ap_vld;
output  [31:0] d_V_out;
output   d_V_out_ap_vld;
output  [31:0] c_V_out;
output   c_V_out_ap_vld;
output  [31:0] b_V_out;
output   b_V_out_ap_vld;
output  [31:0] a_V_2_out;
output   a_V_2_out_ap_vld;

reg ap_idle;
reg h_val_V_out_ap_vld;
reg g_V_out_ap_vld;
reg f_V_out_ap_vld;
reg e_V_2_out_ap_vld;
reg d_V_out_ap_vld;
reg c_V_out_ap_vld;
reg b_V_out_ap_vld;
reg a_V_2_out_ap_vld;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_pp0_stage1_subdone;
reg   [0:0] icmp_ln30_reg_1312;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [5:0] k_V_address0;
reg    k_V_ce0;
wire   [31:0] k_V_q0;
wire   [0:0] icmp_ln30_fu_769_p2;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [31:0] tmp_4_fu_790_p66;
reg   [31:0] tmp_4_reg_1321;
reg   [31:0] a_V_2_reg_1326;
wire    ap_block_pp0_stage1_11001;
reg   [31:0] c_V_reg_1338;
wire   [31:0] t1_V_fu_1070_p2;
reg   [31:0] t1_V_reg_1345;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage0_subdone;
wire   [63:0] zext_ln30_fu_781_p1;
wire    ap_block_pp0_stage0;
reg   [31:0] c_V_1_fu_232;
wire    ap_loop_init;
wire    ap_block_pp0_stage1;
reg   [31:0] d_V_fu_236;
reg   [31:0] g_V_1_fu_240;
reg   [31:0] b_V_fu_244;
wire   [31:0] a_V_fu_1200_p2;
reg   [31:0] h_val_V_fu_248;
reg   [6:0] i_fu_252;
wire   [6:0] add_ln30_fu_775_p2;
reg   [6:0] ap_sig_allocacmp_i_1;
reg   [31:0] d_V_1_fu_256;
reg   [31:0] f_V_fu_260;
wire   [31:0] e_V_fu_1190_p2;
reg   [31:0] h_val_V_1_fu_264;
wire    ap_block_pp0_stage1_01001;
wire   [5:0] tmp_4_fu_790_p65;
wire   [5:0] trunc_ln1669_fu_961_p1;
wire   [25:0] r_V_5_fu_951_p4;
wire   [10:0] trunc_ln1669_1_fu_983_p1;
wire   [20:0] r_V_6_fu_973_p4;
wire   [24:0] trunc_ln1669_2_fu_1005_p1;
wire   [6:0] r_V_7_fu_995_p4;
wire   [31:0] ret_V_12_fu_965_p3;
wire   [31:0] ret_V_13_fu_987_p3;
wire   [31:0] xor_ln1499_fu_1017_p2;
wire   [31:0] ret_V_14_fu_1009_p3;
wire   [31:0] r_V_fu_1035_p2;
wire   [31:0] ret_V_15_fu_1029_p2;
wire   [31:0] ret_V_16_fu_1041_p2;
wire   [31:0] ret_V_4_fu_1047_p2;
wire   [31:0] add_ln186_1_fu_1059_p2;
wire   [31:0] ret_V_fu_1023_p2;
wire   [31:0] add_ln186_2_fu_1064_p2;
wire   [31:0] add_ln186_fu_1053_p2;
wire   [1:0] trunc_ln1669_3_fu_1106_p1;
wire   [29:0] r_V_8_fu_1097_p4;
wire   [12:0] trunc_ln1669_4_fu_1126_p1;
wire   [18:0] r_V_9_fu_1117_p4;
wire   [21:0] trunc_ln1669_5_fu_1146_p1;
wire   [9:0] r_V_s_fu_1137_p4;
wire   [31:0] ret_V_17_fu_1109_p3;
wire   [31:0] ret_V_18_fu_1129_p3;
wire   [31:0] xor_ln1499_3_fu_1157_p2;
wire   [31:0] ret_V_19_fu_1149_p3;
wire   [31:0] xor_ln1499_5_fu_1169_p2;
wire   [31:0] ret_V_20_fu_1174_p2;
wire   [31:0] ret_V_21_fu_1179_p2;
wire   [31:0] ret_V_11_fu_1184_p2;
wire   [31:0] add_ln186_5_fu_1195_p2;
wire   [31:0] ret_V_8_fu_1163_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_1to1;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

sha256_acc_sha256_acc_Pipeline_VITIS_LOOP_30_3_k_V_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
k_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_V_address0),
    .ce0(k_V_ce0),
    .q0(k_V_q0)
);

sha256_acc_mux_646_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 32 ),
    .din26_WIDTH( 32 ),
    .din27_WIDTH( 32 ),
    .din28_WIDTH( 32 ),
    .din29_WIDTH( 32 ),
    .din30_WIDTH( 32 ),
    .din31_WIDTH( 32 ),
    .din32_WIDTH( 32 ),
    .din33_WIDTH( 32 ),
    .din34_WIDTH( 32 ),
    .din35_WIDTH( 32 ),
    .din36_WIDTH( 32 ),
    .din37_WIDTH( 32 ),
    .din38_WIDTH( 32 ),
    .din39_WIDTH( 32 ),
    .din40_WIDTH( 32 ),
    .din41_WIDTH( 32 ),
    .din42_WIDTH( 32 ),
    .din43_WIDTH( 32 ),
    .din44_WIDTH( 32 ),
    .din45_WIDTH( 32 ),
    .din46_WIDTH( 32 ),
    .din47_WIDTH( 32 ),
    .din48_WIDTH( 32 ),
    .din49_WIDTH( 32 ),
    .din50_WIDTH( 32 ),
    .din51_WIDTH( 32 ),
    .din52_WIDTH( 32 ),
    .din53_WIDTH( 32 ),
    .din54_WIDTH( 32 ),
    .din55_WIDTH( 32 ),
    .din56_WIDTH( 32 ),
    .din57_WIDTH( 32 ),
    .din58_WIDTH( 32 ),
    .din59_WIDTH( 32 ),
    .din60_WIDTH( 32 ),
    .din61_WIDTH( 32 ),
    .din62_WIDTH( 32 ),
    .din63_WIDTH( 32 ),
    .din64_WIDTH( 6 ),
    .dout_WIDTH( 32 ))
mux_646_32_1_1_U87(
    .din0(w_V_reload),
    .din1(w_V_1_reload),
    .din2(w_V_2_reload),
    .din3(w_V_3_reload),
    .din4(w_V_4_reload),
    .din5(w_V_5_reload),
    .din6(w_V_6_reload),
    .din7(w_V_7_reload),
    .din8(w_V_8_reload),
    .din9(w_V_9_reload),
    .din10(w_V_10_reload),
    .din11(w_V_11_reload),
    .din12(w_V_12_reload),
    .din13(w_V_13_reload),
    .din14(w_V_14_reload),
    .din15(w_V_15_reload),
    .din16(w_V_33_reload),
    .din17(w_V_34_reload),
    .din18(w_V_35_reload),
    .din19(w_V_36_reload),
    .din20(w_V_37_reload),
    .din21(w_V_38_reload),
    .din22(w_V_39_reload),
    .din23(w_V_40_reload),
    .din24(w_V_41_reload),
    .din25(w_V_42_reload),
    .din26(w_V_43_reload),
    .din27(w_V_44_reload),
    .din28(w_V_45_reload),
    .din29(w_V_46_reload),
    .din30(w_V_47_reload),
    .din31(w_V_48_reload),
    .din32(w_V_49_reload),
    .din33(w_V_50_reload),
    .din34(w_V_51_reload),
    .din35(w_V_52_reload),
    .din36(w_V_53_reload),
    .din37(w_V_54_reload),
    .din38(w_V_55_reload),
    .din39(w_V_56_reload),
    .din40(w_V_57_reload),
    .din41(w_V_58_reload),
    .din42(w_V_59_reload),
    .din43(w_V_60_reload),
    .din44(w_V_61_reload),
    .din45(w_V_62_reload),
    .din46(w_V_63_reload),
    .din47(w_V_64_reload),
    .din48(w_V_65_reload),
    .din49(w_V_66_reload),
    .din50(w_V_67_reload),
    .din51(w_V_68_reload),
    .din52(w_V_69_reload),
    .din53(w_V_70_reload),
    .din54(w_V_71_reload),
    .din55(w_V_72_reload),
    .din56(w_V_73_reload),
    .din57(w_V_74_reload),
    .din58(w_V_75_reload),
    .din59(w_V_76_reload),
    .din60(w_V_77_reload),
    .din61(w_V_78_reload),
    .din62(w_V_79_reload),
    .din63(w_V_80_reload),
    .din64(tmp_4_fu_790_p65),
    .dout(tmp_4_fu_790_p66)
);

sha256_acc_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_exit_pp0_iter0_stage1) | ((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            b_V_fu_244 <= 32'd1779033703;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            b_V_fu_244 <= a_V_fu_1200_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            c_V_1_fu_232 <= 32'd3144134277;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            c_V_1_fu_232 <= a_V_2_reg_1326;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            d_V_1_fu_256 <= 32'd1013904242;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            d_V_1_fu_256 <= c_V_1_fu_232;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            d_V_fu_236 <= 32'd2773480762;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            d_V_fu_236 <= c_V_reg_1338;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            f_V_fu_260 <= 32'd1359893119;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            f_V_fu_260 <= e_V_fu_1190_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        g_V_1_fu_240 <= 32'd2600822924;
    end else if (((icmp_ln30_reg_1312 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        g_V_1_fu_240 <= f_V_fu_260;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        h_val_V_1_fu_264 <= 32'd528734635;
    end else if (((icmp_ln30_reg_1312 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        h_val_V_1_fu_264 <= g_V_1_fu_240;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        h_val_V_fu_248 <= 32'd1541459225;
    end else if (((icmp_ln30_reg_1312 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        h_val_V_fu_248 <= h_val_V_1_fu_264;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln30_fu_769_p2 == 1'd0))) begin
            i_fu_252 <= add_ln30_fu_775_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_252 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        a_V_2_reg_1326 <= b_V_fu_244;
        c_V_reg_1338 <= d_V_1_fu_256;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln30_reg_1312 <= icmp_ln30_fu_769_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln30_reg_1312 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        t1_V_reg_1345 <= t1_V_fu_1070_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln30_fu_769_p2 == 1'd0))) begin
        tmp_4_reg_1321 <= tmp_4_fu_790_p66;
    end
end

always @ (*) begin
    if (((icmp_ln30_reg_1312 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        a_V_2_out_ap_vld = 1'b1;
    end else begin
        a_V_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln30_reg_1312 == 1'd1) & (1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 7'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_252;
    end
end

always @ (*) begin
    if (((icmp_ln30_reg_1312 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b_V_out_ap_vld = 1'b1;
    end else begin
        b_V_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln30_reg_1312 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        c_V_out_ap_vld = 1'b1;
    end else begin
        c_V_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln30_reg_1312 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        d_V_out_ap_vld = 1'b1;
    end else begin
        d_V_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln30_reg_1312 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        e_V_2_out_ap_vld = 1'b1;
    end else begin
        e_V_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln30_reg_1312 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        f_V_out_ap_vld = 1'b1;
    end else begin
        f_V_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln30_reg_1312 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        g_V_out_ap_vld = 1'b1;
    end else begin
        g_V_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln30_reg_1312 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        h_val_V_out_ap_vld = 1'b1;
    end else begin
        h_val_V_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_V_ce0 = 1'b1;
    end else begin
        k_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_V_2_out = b_V_fu_244;

assign a_V_fu_1200_p2 = (add_ln186_5_fu_1195_p2 + ret_V_8_fu_1163_p2);

assign add_ln186_1_fu_1059_p2 = (ret_V_4_fu_1047_p2 + tmp_4_reg_1321);

assign add_ln186_2_fu_1064_p2 = (add_ln186_1_fu_1059_p2 + ret_V_fu_1023_p2);

assign add_ln186_5_fu_1195_p2 = (t1_V_reg_1345 + ret_V_11_fu_1184_p2);

assign add_ln186_fu_1053_p2 = (k_V_q0 + h_val_V_fu_248);

assign add_ln30_fu_775_p2 = (ap_sig_allocacmp_i_1 + 7'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign b_V_out = c_V_1_fu_232;

assign c_V_out = d_V_1_fu_256;

assign d_V_out = d_V_fu_236;

assign e_V_2_out = f_V_fu_260;

assign e_V_fu_1190_p2 = (t1_V_reg_1345 + d_V_fu_236);

assign f_V_out = g_V_1_fu_240;

assign g_V_out = h_val_V_1_fu_264;

assign h_val_V_out = h_val_V_fu_248;

assign icmp_ln30_fu_769_p2 = ((ap_sig_allocacmp_i_1 == 7'd64) ? 1'b1 : 1'b0);

assign k_V_address0 = zext_ln30_fu_781_p1;

assign r_V_5_fu_951_p4 = {{f_V_fu_260[31:6]}};

assign r_V_6_fu_973_p4 = {{f_V_fu_260[31:11]}};

assign r_V_7_fu_995_p4 = {{f_V_fu_260[31:25]}};

assign r_V_8_fu_1097_p4 = {{a_V_2_reg_1326[31:2]}};

assign r_V_9_fu_1117_p4 = {{a_V_2_reg_1326[31:13]}};

assign r_V_fu_1035_p2 = (f_V_fu_260 ^ 32'd4294967295);

assign r_V_s_fu_1137_p4 = {{a_V_2_reg_1326[31:22]}};

assign ret_V_11_fu_1184_p2 = (ret_V_21_fu_1179_p2 ^ ret_V_20_fu_1174_p2);

assign ret_V_12_fu_965_p3 = {{trunc_ln1669_fu_961_p1}, {r_V_5_fu_951_p4}};

assign ret_V_13_fu_987_p3 = {{trunc_ln1669_1_fu_983_p1}, {r_V_6_fu_973_p4}};

assign ret_V_14_fu_1009_p3 = {{trunc_ln1669_2_fu_1005_p1}, {r_V_7_fu_995_p4}};

assign ret_V_15_fu_1029_p2 = (g_V_1_fu_240 & f_V_fu_260);

assign ret_V_16_fu_1041_p2 = (r_V_fu_1035_p2 & h_val_V_1_fu_264);

assign ret_V_17_fu_1109_p3 = {{trunc_ln1669_3_fu_1106_p1}, {r_V_8_fu_1097_p4}};

assign ret_V_18_fu_1129_p3 = {{trunc_ln1669_4_fu_1126_p1}, {r_V_9_fu_1117_p4}};

assign ret_V_19_fu_1149_p3 = {{trunc_ln1669_5_fu_1146_p1}, {r_V_s_fu_1137_p4}};

assign ret_V_20_fu_1174_p2 = (xor_ln1499_5_fu_1169_p2 & a_V_2_reg_1326);

assign ret_V_21_fu_1179_p2 = (c_V_reg_1338 & c_V_1_fu_232);

assign ret_V_4_fu_1047_p2 = (ret_V_16_fu_1041_p2 ^ ret_V_15_fu_1029_p2);

assign ret_V_8_fu_1163_p2 = (xor_ln1499_3_fu_1157_p2 ^ ret_V_19_fu_1149_p3);

assign ret_V_fu_1023_p2 = (xor_ln1499_fu_1017_p2 ^ ret_V_14_fu_1009_p3);

assign t1_V_fu_1070_p2 = (add_ln186_2_fu_1064_p2 + add_ln186_fu_1053_p2);

assign tmp_4_fu_790_p65 = ap_sig_allocacmp_i_1[5:0];

assign trunc_ln1669_1_fu_983_p1 = f_V_fu_260[10:0];

assign trunc_ln1669_2_fu_1005_p1 = f_V_fu_260[24:0];

assign trunc_ln1669_3_fu_1106_p1 = a_V_2_reg_1326[1:0];

assign trunc_ln1669_4_fu_1126_p1 = a_V_2_reg_1326[12:0];

assign trunc_ln1669_5_fu_1146_p1 = a_V_2_reg_1326[21:0];

assign trunc_ln1669_fu_961_p1 = f_V_fu_260[5:0];

assign xor_ln1499_3_fu_1157_p2 = (ret_V_18_fu_1129_p3 ^ ret_V_17_fu_1109_p3);

assign xor_ln1499_5_fu_1169_p2 = (c_V_reg_1338 ^ c_V_1_fu_232);

assign xor_ln1499_fu_1017_p2 = (ret_V_13_fu_987_p3 ^ ret_V_12_fu_965_p3);

assign zext_ln30_fu_781_p1 = ap_sig_allocacmp_i_1;

endmodule //sha256_acc_sha256_acc_Pipeline_VITIS_LOOP_30_3
