// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sha256_acc_sha256_acc_Pipeline_VITIS_LOOP_21_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        w_V_14_reload,
        w_V_15_reload,
        w_V_9_reload,
        w_V_10_reload,
        w_V_11_reload,
        w_V_12_reload,
        w_V_13_reload,
        w_V_1_reload,
        w_V_2_reload,
        w_V_3_reload,
        w_V_4_reload,
        w_V_5_reload,
        w_V_6_reload,
        w_V_7_reload,
        w_V_8_reload,
        w_V_reload,
        w_V_80_out,
        w_V_80_out_ap_vld,
        w_V_79_out,
        w_V_79_out_ap_vld,
        w_V_78_out,
        w_V_78_out_ap_vld,
        w_V_77_out,
        w_V_77_out_ap_vld,
        w_V_76_out,
        w_V_76_out_ap_vld,
        w_V_75_out,
        w_V_75_out_ap_vld,
        w_V_74_out,
        w_V_74_out_ap_vld,
        w_V_73_out,
        w_V_73_out_ap_vld,
        w_V_72_out,
        w_V_72_out_ap_vld,
        w_V_71_out,
        w_V_71_out_ap_vld,
        w_V_70_out,
        w_V_70_out_ap_vld,
        w_V_69_out,
        w_V_69_out_ap_vld,
        w_V_68_out,
        w_V_68_out_ap_vld,
        w_V_67_out,
        w_V_67_out_ap_vld,
        w_V_66_out,
        w_V_66_out_ap_vld,
        w_V_65_out,
        w_V_65_out_ap_vld,
        w_V_64_out,
        w_V_64_out_ap_vld,
        w_V_63_out,
        w_V_63_out_ap_vld,
        w_V_62_out,
        w_V_62_out_ap_vld,
        w_V_61_out,
        w_V_61_out_ap_vld,
        w_V_60_out,
        w_V_60_out_ap_vld,
        w_V_59_out,
        w_V_59_out_ap_vld,
        w_V_58_out,
        w_V_58_out_ap_vld,
        w_V_57_out,
        w_V_57_out_ap_vld,
        w_V_56_out,
        w_V_56_out_ap_vld,
        w_V_55_out,
        w_V_55_out_ap_vld,
        w_V_54_out,
        w_V_54_out_ap_vld,
        w_V_53_out,
        w_V_53_out_ap_vld,
        w_V_52_out,
        w_V_52_out_ap_vld,
        w_V_51_out,
        w_V_51_out_ap_vld,
        w_V_50_out,
        w_V_50_out_ap_vld,
        w_V_49_out,
        w_V_49_out_ap_vld,
        w_V_48_out,
        w_V_48_out_ap_vld,
        w_V_47_out,
        w_V_47_out_ap_vld,
        w_V_46_out,
        w_V_46_out_ap_vld,
        w_V_45_out,
        w_V_45_out_ap_vld,
        w_V_44_out,
        w_V_44_out_ap_vld,
        w_V_43_out,
        w_V_43_out_ap_vld,
        w_V_42_out,
        w_V_42_out_ap_vld,
        w_V_41_out,
        w_V_41_out_ap_vld,
        w_V_40_out,
        w_V_40_out_ap_vld,
        w_V_39_out,
        w_V_39_out_ap_vld,
        w_V_38_out,
        w_V_38_out_ap_vld,
        w_V_37_out,
        w_V_37_out_ap_vld,
        w_V_36_out,
        w_V_36_out_ap_vld,
        w_V_35_out,
        w_V_35_out_ap_vld,
        w_V_34_out,
        w_V_34_out_ap_vld,
        w_V_33_out,
        w_V_33_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] w_V_14_reload;
input  [31:0] w_V_15_reload;
input  [31:0] w_V_9_reload;
input  [31:0] w_V_10_reload;
input  [31:0] w_V_11_reload;
input  [31:0] w_V_12_reload;
input  [31:0] w_V_13_reload;
input  [31:0] w_V_1_reload;
input  [31:0] w_V_2_reload;
input  [31:0] w_V_3_reload;
input  [31:0] w_V_4_reload;
input  [31:0] w_V_5_reload;
input  [31:0] w_V_6_reload;
input  [31:0] w_V_7_reload;
input  [31:0] w_V_8_reload;
input  [31:0] w_V_reload;
output  [31:0] w_V_80_out;
output   w_V_80_out_ap_vld;
output  [31:0] w_V_79_out;
output   w_V_79_out_ap_vld;
output  [31:0] w_V_78_out;
output   w_V_78_out_ap_vld;
output  [31:0] w_V_77_out;
output   w_V_77_out_ap_vld;
output  [31:0] w_V_76_out;
output   w_V_76_out_ap_vld;
output  [31:0] w_V_75_out;
output   w_V_75_out_ap_vld;
output  [31:0] w_V_74_out;
output   w_V_74_out_ap_vld;
output  [31:0] w_V_73_out;
output   w_V_73_out_ap_vld;
output  [31:0] w_V_72_out;
output   w_V_72_out_ap_vld;
output  [31:0] w_V_71_out;
output   w_V_71_out_ap_vld;
output  [31:0] w_V_70_out;
output   w_V_70_out_ap_vld;
output  [31:0] w_V_69_out;
output   w_V_69_out_ap_vld;
output  [31:0] w_V_68_out;
output   w_V_68_out_ap_vld;
output  [31:0] w_V_67_out;
output   w_V_67_out_ap_vld;
output  [31:0] w_V_66_out;
output   w_V_66_out_ap_vld;
output  [31:0] w_V_65_out;
output   w_V_65_out_ap_vld;
output  [31:0] w_V_64_out;
output   w_V_64_out_ap_vld;
output  [31:0] w_V_63_out;
output   w_V_63_out_ap_vld;
output  [31:0] w_V_62_out;
output   w_V_62_out_ap_vld;
output  [31:0] w_V_61_out;
output   w_V_61_out_ap_vld;
output  [31:0] w_V_60_out;
output   w_V_60_out_ap_vld;
output  [31:0] w_V_59_out;
output   w_V_59_out_ap_vld;
output  [31:0] w_V_58_out;
output   w_V_58_out_ap_vld;
output  [31:0] w_V_57_out;
output   w_V_57_out_ap_vld;
output  [31:0] w_V_56_out;
output   w_V_56_out_ap_vld;
output  [31:0] w_V_55_out;
output   w_V_55_out_ap_vld;
output  [31:0] w_V_54_out;
output   w_V_54_out_ap_vld;
output  [31:0] w_V_53_out;
output   w_V_53_out_ap_vld;
output  [31:0] w_V_52_out;
output   w_V_52_out_ap_vld;
output  [31:0] w_V_51_out;
output   w_V_51_out_ap_vld;
output  [31:0] w_V_50_out;
output   w_V_50_out_ap_vld;
output  [31:0] w_V_49_out;
output   w_V_49_out_ap_vld;
output  [31:0] w_V_48_out;
output   w_V_48_out_ap_vld;
output  [31:0] w_V_47_out;
output   w_V_47_out_ap_vld;
output  [31:0] w_V_46_out;
output   w_V_46_out_ap_vld;
output  [31:0] w_V_45_out;
output   w_V_45_out_ap_vld;
output  [31:0] w_V_44_out;
output   w_V_44_out_ap_vld;
output  [31:0] w_V_43_out;
output   w_V_43_out_ap_vld;
output  [31:0] w_V_42_out;
output   w_V_42_out_ap_vld;
output  [31:0] w_V_41_out;
output   w_V_41_out_ap_vld;
output  [31:0] w_V_40_out;
output   w_V_40_out_ap_vld;
output  [31:0] w_V_39_out;
output   w_V_39_out_ap_vld;
output  [31:0] w_V_38_out;
output   w_V_38_out_ap_vld;
output  [31:0] w_V_37_out;
output   w_V_37_out_ap_vld;
output  [31:0] w_V_36_out;
output   w_V_36_out_ap_vld;
output  [31:0] w_V_35_out;
output   w_V_35_out_ap_vld;
output  [31:0] w_V_34_out;
output   w_V_34_out_ap_vld;
output  [31:0] w_V_33_out;
output   w_V_33_out_ap_vld;

reg ap_idle;
reg w_V_80_out_ap_vld;
reg w_V_79_out_ap_vld;
reg w_V_78_out_ap_vld;
reg w_V_77_out_ap_vld;
reg w_V_76_out_ap_vld;
reg w_V_75_out_ap_vld;
reg w_V_74_out_ap_vld;
reg w_V_73_out_ap_vld;
reg w_V_72_out_ap_vld;
reg w_V_71_out_ap_vld;
reg w_V_70_out_ap_vld;
reg w_V_69_out_ap_vld;
reg w_V_68_out_ap_vld;
reg w_V_67_out_ap_vld;
reg w_V_66_out_ap_vld;
reg w_V_65_out_ap_vld;
reg w_V_64_out_ap_vld;
reg w_V_63_out_ap_vld;
reg w_V_62_out_ap_vld;
reg w_V_61_out_ap_vld;
reg w_V_60_out_ap_vld;
reg w_V_59_out_ap_vld;
reg w_V_58_out_ap_vld;
reg w_V_57_out_ap_vld;
reg w_V_56_out_ap_vld;
reg w_V_55_out_ap_vld;
reg w_V_54_out_ap_vld;
reg w_V_53_out_ap_vld;
reg w_V_52_out_ap_vld;
reg w_V_51_out_ap_vld;
reg w_V_50_out_ap_vld;
reg w_V_49_out_ap_vld;
reg w_V_48_out_ap_vld;
reg w_V_47_out_ap_vld;
reg w_V_46_out_ap_vld;
reg w_V_45_out_ap_vld;
reg w_V_44_out_ap_vld;
reg w_V_43_out_ap_vld;
reg w_V_42_out_ap_vld;
reg w_V_41_out_ap_vld;
reg w_V_40_out_ap_vld;
reg w_V_39_out_ap_vld;
reg w_V_38_out_ap_vld;
reg w_V_37_out_ap_vld;
reg w_V_36_out_ap_vld;
reg w_V_35_out_ap_vld;
reg w_V_34_out_ap_vld;
reg w_V_33_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln21_fu_924_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [6:0] i_1_fu_288;
wire   [6:0] add_ln21_fu_2006_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_i;
reg   [31:0] w_V_fu_292;
wire   [31:0] w_V_48_fu_1760_p2;
wire   [5:0] trunc_ln1669_fu_1068_p1;
reg   [31:0] w_V_1_fu_296;
reg   [31:0] w_V_2_fu_300;
reg   [31:0] w_V_3_fu_304;
reg   [31:0] w_V_4_fu_308;
reg   [31:0] w_V_5_fu_312;
reg   [31:0] w_V_6_fu_316;
reg   [31:0] w_V_7_fu_320;
reg   [31:0] w_V_8_fu_324;
reg   [31:0] w_V_9_fu_328;
reg   [31:0] w_V_10_fu_332;
reg   [31:0] w_V_11_fu_336;
reg   [31:0] w_V_12_fu_340;
reg   [31:0] w_V_13_fu_344;
reg   [31:0] w_V_14_fu_348;
reg   [31:0] w_V_15_fu_352;
reg   [31:0] w_V_16_fu_356;
reg   [31:0] w_V_17_fu_360;
reg   [31:0] w_V_18_fu_364;
reg   [31:0] w_V_19_fu_368;
reg   [31:0] w_V_20_fu_372;
reg   [31:0] w_V_21_fu_376;
reg   [31:0] w_V_22_fu_380;
reg   [31:0] w_V_23_fu_384;
reg   [31:0] w_V_24_fu_388;
reg   [31:0] w_V_25_fu_392;
reg   [31:0] w_V_26_fu_396;
reg   [31:0] w_V_27_fu_400;
reg   [31:0] w_V_28_fu_404;
reg   [31:0] w_V_29_fu_408;
reg   [31:0] w_V_30_fu_412;
reg   [31:0] w_V_31_fu_416;
reg   [31:0] w_V_32_fu_420;
reg   [31:0] w_V_33_fu_424;
reg   [31:0] w_V_34_fu_428;
reg   [31:0] w_V_35_fu_432;
reg   [31:0] w_V_36_fu_436;
reg   [31:0] w_V_37_fu_440;
reg   [31:0] w_V_38_fu_444;
reg   [31:0] w_V_39_fu_448;
reg   [31:0] w_V_40_fu_452;
reg   [31:0] w_V_41_fu_456;
reg   [31:0] w_V_42_fu_460;
reg   [31:0] w_V_43_fu_464;
reg   [31:0] w_V_44_fu_468;
reg   [31:0] w_V_45_fu_472;
reg   [31:0] w_V_46_fu_476;
reg   [31:0] w_V_47_fu_480;
wire   [31:0] tmp_fu_1072_p66;
wire   [16:0] trunc_ln1669_6_fu_1216_p1;
wire   [14:0] r_V_fu_1206_p4;
wire   [18:0] trunc_ln1669_7_fu_1238_p1;
wire   [12:0] r_V_s_fu_1228_p4;
wire   [21:0] r_V_5_fu_1250_p4;
wire   [31:0] ret_V_29_fu_1220_p3;
wire   [31:0] zext_ln1669_fu_1260_p1;
wire   [31:0] xor_ln1499_fu_1264_p2;
wire   [31:0] ret_V_30_fu_1242_p3;
wire   [31:0] tmp_2_fu_1410_p66;
wire   [6:0] trunc_ln1669_8_fu_1554_p1;
wire   [24:0] r_V_2_fu_1544_p4;
wire   [17:0] trunc_ln1669_9_fu_1576_p1;
wire   [13:0] r_V_3_fu_1566_p4;
wire   [28:0] r_V_6_fu_1588_p4;
wire   [31:0] zext_ln1669_1_fu_1598_p1;
wire   [31:0] ret_V_32_fu_1580_p3;
wire   [31:0] xor_ln1499_2_fu_1602_p2;
wire   [31:0] ret_V_31_fu_1558_p3;
wire   [31:0] tmp_3_fu_1614_p66;
wire   [31:0] ret_V_28_fu_1608_p2;
wire   [31:0] ret_V_fu_1270_p2;
wire   [31:0] tmp_1_fu_1276_p66;
wire   [31:0] add_ln186_fu_1754_p2;
wire   [31:0] add_ln186_1_fu_1748_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

sha256_acc_mux_646_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 32 ),
    .din26_WIDTH( 32 ),
    .din27_WIDTH( 32 ),
    .din28_WIDTH( 32 ),
    .din29_WIDTH( 32 ),
    .din30_WIDTH( 32 ),
    .din31_WIDTH( 32 ),
    .din32_WIDTH( 32 ),
    .din33_WIDTH( 32 ),
    .din34_WIDTH( 32 ),
    .din35_WIDTH( 32 ),
    .din36_WIDTH( 32 ),
    .din37_WIDTH( 32 ),
    .din38_WIDTH( 32 ),
    .din39_WIDTH( 32 ),
    .din40_WIDTH( 32 ),
    .din41_WIDTH( 32 ),
    .din42_WIDTH( 32 ),
    .din43_WIDTH( 32 ),
    .din44_WIDTH( 32 ),
    .din45_WIDTH( 32 ),
    .din46_WIDTH( 32 ),
    .din47_WIDTH( 32 ),
    .din48_WIDTH( 32 ),
    .din49_WIDTH( 32 ),
    .din50_WIDTH( 32 ),
    .din51_WIDTH( 32 ),
    .din52_WIDTH( 32 ),
    .din53_WIDTH( 32 ),
    .din54_WIDTH( 32 ),
    .din55_WIDTH( 32 ),
    .din56_WIDTH( 32 ),
    .din57_WIDTH( 32 ),
    .din58_WIDTH( 32 ),
    .din59_WIDTH( 32 ),
    .din60_WIDTH( 32 ),
    .din61_WIDTH( 32 ),
    .din62_WIDTH( 32 ),
    .din63_WIDTH( 32 ),
    .din64_WIDTH( 6 ),
    .dout_WIDTH( 32 ))
mux_646_32_1_1_U18(
    .din0(32'd0),
    .din1(32'd0),
    .din2(32'd0),
    .din3(32'd0),
    .din4(32'd0),
    .din5(32'd0),
    .din6(32'd0),
    .din7(32'd0),
    .din8(32'd0),
    .din9(32'd0),
    .din10(32'd0),
    .din11(32'd0),
    .din12(32'd0),
    .din13(32'd0),
    .din14(32'd0),
    .din15(32'd0),
    .din16(w_V_14_reload),
    .din17(w_V_15_reload),
    .din18(w_V_fu_292),
    .din19(w_V_1_fu_296),
    .din20(w_V_2_fu_300),
    .din21(w_V_3_fu_304),
    .din22(w_V_4_fu_308),
    .din23(w_V_5_fu_312),
    .din24(w_V_6_fu_316),
    .din25(w_V_7_fu_320),
    .din26(w_V_8_fu_324),
    .din27(w_V_9_fu_328),
    .din28(w_V_10_fu_332),
    .din29(w_V_11_fu_336),
    .din30(w_V_12_fu_340),
    .din31(w_V_13_fu_344),
    .din32(w_V_14_fu_348),
    .din33(w_V_15_fu_352),
    .din34(w_V_16_fu_356),
    .din35(w_V_17_fu_360),
    .din36(w_V_18_fu_364),
    .din37(w_V_19_fu_368),
    .din38(w_V_20_fu_372),
    .din39(w_V_21_fu_376),
    .din40(w_V_22_fu_380),
    .din41(w_V_23_fu_384),
    .din42(w_V_24_fu_388),
    .din43(w_V_25_fu_392),
    .din44(w_V_26_fu_396),
    .din45(w_V_27_fu_400),
    .din46(w_V_28_fu_404),
    .din47(w_V_29_fu_408),
    .din48(w_V_30_fu_412),
    .din49(w_V_31_fu_416),
    .din50(w_V_32_fu_420),
    .din51(w_V_33_fu_424),
    .din52(w_V_34_fu_428),
    .din53(w_V_35_fu_432),
    .din54(w_V_36_fu_436),
    .din55(w_V_37_fu_440),
    .din56(w_V_38_fu_444),
    .din57(w_V_39_fu_448),
    .din58(w_V_40_fu_452),
    .din59(w_V_41_fu_456),
    .din60(w_V_42_fu_460),
    .din61(w_V_43_fu_464),
    .din62(w_V_44_fu_468),
    .din63(w_V_45_fu_472),
    .din64(trunc_ln1669_fu_1068_p1),
    .dout(tmp_fu_1072_p66)
);

sha256_acc_mux_646_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 32 ),
    .din26_WIDTH( 32 ),
    .din27_WIDTH( 32 ),
    .din28_WIDTH( 32 ),
    .din29_WIDTH( 32 ),
    .din30_WIDTH( 32 ),
    .din31_WIDTH( 32 ),
    .din32_WIDTH( 32 ),
    .din33_WIDTH( 32 ),
    .din34_WIDTH( 32 ),
    .din35_WIDTH( 32 ),
    .din36_WIDTH( 32 ),
    .din37_WIDTH( 32 ),
    .din38_WIDTH( 32 ),
    .din39_WIDTH( 32 ),
    .din40_WIDTH( 32 ),
    .din41_WIDTH( 32 ),
    .din42_WIDTH( 32 ),
    .din43_WIDTH( 32 ),
    .din44_WIDTH( 32 ),
    .din45_WIDTH( 32 ),
    .din46_WIDTH( 32 ),
    .din47_WIDTH( 32 ),
    .din48_WIDTH( 32 ),
    .din49_WIDTH( 32 ),
    .din50_WIDTH( 32 ),
    .din51_WIDTH( 32 ),
    .din52_WIDTH( 32 ),
    .din53_WIDTH( 32 ),
    .din54_WIDTH( 32 ),
    .din55_WIDTH( 32 ),
    .din56_WIDTH( 32 ),
    .din57_WIDTH( 32 ),
    .din58_WIDTH( 32 ),
    .din59_WIDTH( 32 ),
    .din60_WIDTH( 32 ),
    .din61_WIDTH( 32 ),
    .din62_WIDTH( 32 ),
    .din63_WIDTH( 32 ),
    .din64_WIDTH( 6 ),
    .dout_WIDTH( 32 ))
mux_646_32_1_1_U19(
    .din0(32'd0),
    .din1(32'd0),
    .din2(32'd0),
    .din3(32'd0),
    .din4(32'd0),
    .din5(32'd0),
    .din6(32'd0),
    .din7(32'd0),
    .din8(32'd0),
    .din9(32'd0),
    .din10(32'd0),
    .din11(32'd0),
    .din12(32'd0),
    .din13(32'd0),
    .din14(32'd0),
    .din15(32'd0),
    .din16(w_V_9_reload),
    .din17(w_V_10_reload),
    .din18(w_V_11_reload),
    .din19(w_V_12_reload),
    .din20(w_V_13_reload),
    .din21(w_V_14_reload),
    .din22(w_V_15_reload),
    .din23(w_V_fu_292),
    .din24(w_V_1_fu_296),
    .din25(w_V_2_fu_300),
    .din26(w_V_3_fu_304),
    .din27(w_V_4_fu_308),
    .din28(w_V_5_fu_312),
    .din29(w_V_6_fu_316),
    .din30(w_V_7_fu_320),
    .din31(w_V_8_fu_324),
    .din32(w_V_9_fu_328),
    .din33(w_V_10_fu_332),
    .din34(w_V_11_fu_336),
    .din35(w_V_12_fu_340),
    .din36(w_V_13_fu_344),
    .din37(w_V_14_fu_348),
    .din38(w_V_15_fu_352),
    .din39(w_V_16_fu_356),
    .din40(w_V_17_fu_360),
    .din41(w_V_18_fu_364),
    .din42(w_V_19_fu_368),
    .din43(w_V_20_fu_372),
    .din44(w_V_21_fu_376),
    .din45(w_V_22_fu_380),
    .din46(w_V_23_fu_384),
    .din47(w_V_24_fu_388),
    .din48(w_V_25_fu_392),
    .din49(w_V_26_fu_396),
    .din50(w_V_27_fu_400),
    .din51(w_V_28_fu_404),
    .din52(w_V_29_fu_408),
    .din53(w_V_30_fu_412),
    .din54(w_V_31_fu_416),
    .din55(w_V_32_fu_420),
    .din56(w_V_33_fu_424),
    .din57(w_V_34_fu_428),
    .din58(w_V_35_fu_432),
    .din59(w_V_36_fu_436),
    .din60(w_V_37_fu_440),
    .din61(w_V_38_fu_444),
    .din62(w_V_39_fu_448),
    .din63(w_V_40_fu_452),
    .din64(trunc_ln1669_fu_1068_p1),
    .dout(tmp_1_fu_1276_p66)
);

sha256_acc_mux_646_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 32 ),
    .din26_WIDTH( 32 ),
    .din27_WIDTH( 32 ),
    .din28_WIDTH( 32 ),
    .din29_WIDTH( 32 ),
    .din30_WIDTH( 32 ),
    .din31_WIDTH( 32 ),
    .din32_WIDTH( 32 ),
    .din33_WIDTH( 32 ),
    .din34_WIDTH( 32 ),
    .din35_WIDTH( 32 ),
    .din36_WIDTH( 32 ),
    .din37_WIDTH( 32 ),
    .din38_WIDTH( 32 ),
    .din39_WIDTH( 32 ),
    .din40_WIDTH( 32 ),
    .din41_WIDTH( 32 ),
    .din42_WIDTH( 32 ),
    .din43_WIDTH( 32 ),
    .din44_WIDTH( 32 ),
    .din45_WIDTH( 32 ),
    .din46_WIDTH( 32 ),
    .din47_WIDTH( 32 ),
    .din48_WIDTH( 32 ),
    .din49_WIDTH( 32 ),
    .din50_WIDTH( 32 ),
    .din51_WIDTH( 32 ),
    .din52_WIDTH( 32 ),
    .din53_WIDTH( 32 ),
    .din54_WIDTH( 32 ),
    .din55_WIDTH( 32 ),
    .din56_WIDTH( 32 ),
    .din57_WIDTH( 32 ),
    .din58_WIDTH( 32 ),
    .din59_WIDTH( 32 ),
    .din60_WIDTH( 32 ),
    .din61_WIDTH( 32 ),
    .din62_WIDTH( 32 ),
    .din63_WIDTH( 32 ),
    .din64_WIDTH( 6 ),
    .dout_WIDTH( 32 ))
mux_646_32_1_1_U20(
    .din0(32'd0),
    .din1(32'd0),
    .din2(32'd0),
    .din3(32'd0),
    .din4(32'd0),
    .din5(32'd0),
    .din6(32'd0),
    .din7(32'd0),
    .din8(32'd0),
    .din9(32'd0),
    .din10(32'd0),
    .din11(32'd0),
    .din12(32'd0),
    .din13(32'd0),
    .din14(32'd0),
    .din15(32'd0),
    .din16(w_V_1_reload),
    .din17(w_V_2_reload),
    .din18(w_V_3_reload),
    .din19(w_V_4_reload),
    .din20(w_V_5_reload),
    .din21(w_V_6_reload),
    .din22(w_V_7_reload),
    .din23(w_V_8_reload),
    .din24(w_V_9_reload),
    .din25(w_V_10_reload),
    .din26(w_V_11_reload),
    .din27(w_V_12_reload),
    .din28(w_V_13_reload),
    .din29(w_V_14_reload),
    .din30(w_V_15_reload),
    .din31(w_V_fu_292),
    .din32(w_V_1_fu_296),
    .din33(w_V_2_fu_300),
    .din34(w_V_3_fu_304),
    .din35(w_V_4_fu_308),
    .din36(w_V_5_fu_312),
    .din37(w_V_6_fu_316),
    .din38(w_V_7_fu_320),
    .din39(w_V_8_fu_324),
    .din40(w_V_9_fu_328),
    .din41(w_V_10_fu_332),
    .din42(w_V_11_fu_336),
    .din43(w_V_12_fu_340),
    .din44(w_V_13_fu_344),
    .din45(w_V_14_fu_348),
    .din46(w_V_15_fu_352),
    .din47(w_V_16_fu_356),
    .din48(w_V_17_fu_360),
    .din49(w_V_18_fu_364),
    .din50(w_V_19_fu_368),
    .din51(w_V_20_fu_372),
    .din52(w_V_21_fu_376),
    .din53(w_V_22_fu_380),
    .din54(w_V_23_fu_384),
    .din55(w_V_24_fu_388),
    .din56(w_V_25_fu_392),
    .din57(w_V_26_fu_396),
    .din58(w_V_27_fu_400),
    .din59(w_V_28_fu_404),
    .din60(w_V_29_fu_408),
    .din61(w_V_30_fu_412),
    .din62(w_V_31_fu_416),
    .din63(w_V_32_fu_420),
    .din64(trunc_ln1669_fu_1068_p1),
    .dout(tmp_2_fu_1410_p66)
);

sha256_acc_mux_646_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 32 ),
    .din26_WIDTH( 32 ),
    .din27_WIDTH( 32 ),
    .din28_WIDTH( 32 ),
    .din29_WIDTH( 32 ),
    .din30_WIDTH( 32 ),
    .din31_WIDTH( 32 ),
    .din32_WIDTH( 32 ),
    .din33_WIDTH( 32 ),
    .din34_WIDTH( 32 ),
    .din35_WIDTH( 32 ),
    .din36_WIDTH( 32 ),
    .din37_WIDTH( 32 ),
    .din38_WIDTH( 32 ),
    .din39_WIDTH( 32 ),
    .din40_WIDTH( 32 ),
    .din41_WIDTH( 32 ),
    .din42_WIDTH( 32 ),
    .din43_WIDTH( 32 ),
    .din44_WIDTH( 32 ),
    .din45_WIDTH( 32 ),
    .din46_WIDTH( 32 ),
    .din47_WIDTH( 32 ),
    .din48_WIDTH( 32 ),
    .din49_WIDTH( 32 ),
    .din50_WIDTH( 32 ),
    .din51_WIDTH( 32 ),
    .din52_WIDTH( 32 ),
    .din53_WIDTH( 32 ),
    .din54_WIDTH( 32 ),
    .din55_WIDTH( 32 ),
    .din56_WIDTH( 32 ),
    .din57_WIDTH( 32 ),
    .din58_WIDTH( 32 ),
    .din59_WIDTH( 32 ),
    .din60_WIDTH( 32 ),
    .din61_WIDTH( 32 ),
    .din62_WIDTH( 32 ),
    .din63_WIDTH( 32 ),
    .din64_WIDTH( 6 ),
    .dout_WIDTH( 32 ))
mux_646_32_1_1_U21(
    .din0(32'd0),
    .din1(32'd0),
    .din2(32'd0),
    .din3(32'd0),
    .din4(32'd0),
    .din5(32'd0),
    .din6(32'd0),
    .din7(32'd0),
    .din8(32'd0),
    .din9(32'd0),
    .din10(32'd0),
    .din11(32'd0),
    .din12(32'd0),
    .din13(32'd0),
    .din14(32'd0),
    .din15(32'd0),
    .din16(w_V_reload),
    .din17(w_V_1_reload),
    .din18(w_V_2_reload),
    .din19(w_V_3_reload),
    .din20(w_V_4_reload),
    .din21(w_V_5_reload),
    .din22(w_V_6_reload),
    .din23(w_V_7_reload),
    .din24(w_V_8_reload),
    .din25(w_V_9_reload),
    .din26(w_V_10_reload),
    .din27(w_V_11_reload),
    .din28(w_V_12_reload),
    .din29(w_V_13_reload),
    .din30(w_V_14_reload),
    .din31(w_V_15_reload),
    .din32(w_V_fu_292),
    .din33(w_V_1_fu_296),
    .din34(w_V_2_fu_300),
    .din35(w_V_3_fu_304),
    .din36(w_V_4_fu_308),
    .din37(w_V_5_fu_312),
    .din38(w_V_6_fu_316),
    .din39(w_V_7_fu_320),
    .din40(w_V_8_fu_324),
    .din41(w_V_9_fu_328),
    .din42(w_V_10_fu_332),
    .din43(w_V_11_fu_336),
    .din44(w_V_12_fu_340),
    .din45(w_V_13_fu_344),
    .din46(w_V_14_fu_348),
    .din47(w_V_15_fu_352),
    .din48(w_V_16_fu_356),
    .din49(w_V_17_fu_360),
    .din50(w_V_18_fu_364),
    .din51(w_V_19_fu_368),
    .din52(w_V_20_fu_372),
    .din53(w_V_21_fu_376),
    .din54(w_V_22_fu_380),
    .din55(w_V_23_fu_384),
    .din56(w_V_24_fu_388),
    .din57(w_V_25_fu_392),
    .din58(w_V_26_fu_396),
    .din59(w_V_27_fu_400),
    .din60(w_V_28_fu_404),
    .din61(w_V_29_fu_408),
    .din62(w_V_30_fu_412),
    .din63(w_V_31_fu_416),
    .din64(trunc_ln1669_fu_1068_p1),
    .dout(tmp_3_fu_1614_p66)
);

sha256_acc_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        if ((icmp_ln21_fu_924_p2 == 1'd0)) begin
            i_1_fu_288 <= add_ln21_fu_2006_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_1_fu_288 <= 7'd16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd26) & (ap_start_int == 1'b1))) begin
        w_V_10_fu_332 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd27) & (ap_start_int == 1'b1))) begin
        w_V_11_fu_336 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd28) & (ap_start_int == 1'b1))) begin
        w_V_12_fu_340 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd29) & (ap_start_int == 1'b1))) begin
        w_V_13_fu_344 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd30) & (ap_start_int == 1'b1))) begin
        w_V_14_fu_348 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd31) & (ap_start_int == 1'b1))) begin
        w_V_15_fu_352 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd32) & (ap_start_int == 1'b1))) begin
        w_V_16_fu_356 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd33) & (ap_start_int == 1'b1))) begin
        w_V_17_fu_360 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd34) & (ap_start_int == 1'b1))) begin
        w_V_18_fu_364 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd35) & (ap_start_int == 1'b1))) begin
        w_V_19_fu_368 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd17) & (ap_start_int == 1'b1))) begin
        w_V_1_fu_296 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd36) & (ap_start_int == 1'b1))) begin
        w_V_20_fu_372 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd37) & (ap_start_int == 1'b1))) begin
        w_V_21_fu_376 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd38) & (ap_start_int == 1'b1))) begin
        w_V_22_fu_380 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd39) & (ap_start_int == 1'b1))) begin
        w_V_23_fu_384 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd40) & (ap_start_int == 1'b1))) begin
        w_V_24_fu_388 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd41) & (ap_start_int == 1'b1))) begin
        w_V_25_fu_392 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd42) & (ap_start_int == 1'b1))) begin
        w_V_26_fu_396 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd43) & (ap_start_int == 1'b1))) begin
        w_V_27_fu_400 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd44) & (ap_start_int == 1'b1))) begin
        w_V_28_fu_404 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd45) & (ap_start_int == 1'b1))) begin
        w_V_29_fu_408 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd18) & (ap_start_int == 1'b1))) begin
        w_V_2_fu_300 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd46) & (ap_start_int == 1'b1))) begin
        w_V_30_fu_412 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd47) & (ap_start_int == 1'b1))) begin
        w_V_31_fu_416 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd48) & (ap_start_int == 1'b1))) begin
        w_V_32_fu_420 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd49) & (ap_start_int == 1'b1))) begin
        w_V_33_fu_424 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd50) & (ap_start_int == 1'b1))) begin
        w_V_34_fu_428 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd51) & (ap_start_int == 1'b1))) begin
        w_V_35_fu_432 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd52) & (ap_start_int == 1'b1))) begin
        w_V_36_fu_436 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd53) & (ap_start_int == 1'b1))) begin
        w_V_37_fu_440 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd54) & (ap_start_int == 1'b1))) begin
        w_V_38_fu_444 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd55) & (ap_start_int == 1'b1))) begin
        w_V_39_fu_448 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd19) & (ap_start_int == 1'b1))) begin
        w_V_3_fu_304 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd56) & (ap_start_int == 1'b1))) begin
        w_V_40_fu_452 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd57) & (ap_start_int == 1'b1))) begin
        w_V_41_fu_456 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd58) & (ap_start_int == 1'b1))) begin
        w_V_42_fu_460 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd59) & (ap_start_int == 1'b1))) begin
        w_V_43_fu_464 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd60) & (ap_start_int == 1'b1))) begin
        w_V_44_fu_468 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd61) & (ap_start_int == 1'b1))) begin
        w_V_45_fu_472 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd62) & (ap_start_int == 1'b1))) begin
        w_V_46_fu_476 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1) & ((((((((((((((((((icmp_ln21_fu_924_p2 == 1'd0) & (trunc_ln1669_fu_1068_p1 == 6'd15)) | ((icmp_ln21_fu_924_p2 == 1'd0) & (trunc_ln1669_fu_1068_p1 == 6'd63))) | ((icmp_ln21_fu_924_p2 == 1'd0) & (trunc_ln1669_fu_1068_p1 == 6'd14))) | ((icmp_ln21_fu_924_p2 == 1'd0) & (trunc_ln1669_fu_1068_p1 == 6'd13))) | ((icmp_ln21_fu_924_p2 == 1'd0) & (trunc_ln1669_fu_1068_p1 == 6'd12))) | ((icmp_ln21_fu_924_p2 == 1'd0) & (trunc_ln1669_fu_1068_p1 == 6'd11))) | ((icmp_ln21_fu_924_p2 == 1'd0) & (trunc_ln1669_fu_1068_p1 == 6'd10))) | ((icmp_ln21_fu_924_p2 == 1'd0) & (trunc_ln1669_fu_1068_p1 == 6'd9))) | ((icmp_ln21_fu_924_p2 == 1'd0) & (trunc_ln1669_fu_1068_p1 == 6'd8))) | ((icmp_ln21_fu_924_p2 == 1'd0) & (trunc_ln1669_fu_1068_p1 == 6'd7))) | ((icmp_ln21_fu_924_p2 == 1'd0) & (trunc_ln1669_fu_1068_p1 == 6'd6))) | ((icmp_ln21_fu_924_p2 == 1'd0) & (trunc_ln1669_fu_1068_p1 == 6'd5))) | ((icmp_ln21_fu_924_p2 == 1'd0) & (trunc_ln1669_fu_1068_p1 == 6'd4))) | ((icmp_ln21_fu_924_p2 == 1'd0) & (trunc_ln1669_fu_1068_p1 == 6'd3))) | ((icmp_ln21_fu_924_p2 == 1'd0) & (trunc_ln1669_fu_1068_p1 == 6'd2))) | ((icmp_ln21_fu_924_p2 == 1'd0) & (trunc_ln1669_fu_1068_p1 == 6'd1))) | ((icmp_ln21_fu_924_p2 == 1'd0) & (trunc_ln1669_fu_1068_p1 == 6'd0))))) begin
        w_V_47_fu_480 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd20) & (ap_start_int == 1'b1))) begin
        w_V_4_fu_308 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd21) & (ap_start_int == 1'b1))) begin
        w_V_5_fu_312 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd22) & (ap_start_int == 1'b1))) begin
        w_V_6_fu_316 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd23) & (ap_start_int == 1'b1))) begin
        w_V_7_fu_320 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd24) & (ap_start_int == 1'b1))) begin
        w_V_8_fu_324 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd25) & (ap_start_int == 1'b1))) begin
        w_V_9_fu_328 <= w_V_48_fu_1760_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln21_fu_924_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln1669_fu_1068_p1 == 6'd16) & (ap_start_int == 1'b1))) begin
        w_V_fu_292 <= w_V_48_fu_1760_p2;
    end
end

always @ (*) begin
    if ((ap_start_int == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i = 7'd16;
    end else begin
        ap_sig_allocacmp_i = i_1_fu_288;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_33_out_ap_vld = 1'b1;
    end else begin
        w_V_33_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_34_out_ap_vld = 1'b1;
    end else begin
        w_V_34_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_35_out_ap_vld = 1'b1;
    end else begin
        w_V_35_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_36_out_ap_vld = 1'b1;
    end else begin
        w_V_36_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_37_out_ap_vld = 1'b1;
    end else begin
        w_V_37_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_38_out_ap_vld = 1'b1;
    end else begin
        w_V_38_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_39_out_ap_vld = 1'b1;
    end else begin
        w_V_39_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_40_out_ap_vld = 1'b1;
    end else begin
        w_V_40_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_41_out_ap_vld = 1'b1;
    end else begin
        w_V_41_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_42_out_ap_vld = 1'b1;
    end else begin
        w_V_42_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_43_out_ap_vld = 1'b1;
    end else begin
        w_V_43_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_44_out_ap_vld = 1'b1;
    end else begin
        w_V_44_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_45_out_ap_vld = 1'b1;
    end else begin
        w_V_45_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_46_out_ap_vld = 1'b1;
    end else begin
        w_V_46_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_47_out_ap_vld = 1'b1;
    end else begin
        w_V_47_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_48_out_ap_vld = 1'b1;
    end else begin
        w_V_48_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_49_out_ap_vld = 1'b1;
    end else begin
        w_V_49_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_50_out_ap_vld = 1'b1;
    end else begin
        w_V_50_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_51_out_ap_vld = 1'b1;
    end else begin
        w_V_51_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_52_out_ap_vld = 1'b1;
    end else begin
        w_V_52_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_53_out_ap_vld = 1'b1;
    end else begin
        w_V_53_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_54_out_ap_vld = 1'b1;
    end else begin
        w_V_54_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_55_out_ap_vld = 1'b1;
    end else begin
        w_V_55_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_56_out_ap_vld = 1'b1;
    end else begin
        w_V_56_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_57_out_ap_vld = 1'b1;
    end else begin
        w_V_57_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_58_out_ap_vld = 1'b1;
    end else begin
        w_V_58_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_59_out_ap_vld = 1'b1;
    end else begin
        w_V_59_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_60_out_ap_vld = 1'b1;
    end else begin
        w_V_60_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_61_out_ap_vld = 1'b1;
    end else begin
        w_V_61_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_62_out_ap_vld = 1'b1;
    end else begin
        w_V_62_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_63_out_ap_vld = 1'b1;
    end else begin
        w_V_63_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_64_out_ap_vld = 1'b1;
    end else begin
        w_V_64_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_65_out_ap_vld = 1'b1;
    end else begin
        w_V_65_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_66_out_ap_vld = 1'b1;
    end else begin
        w_V_66_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_67_out_ap_vld = 1'b1;
    end else begin
        w_V_67_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_68_out_ap_vld = 1'b1;
    end else begin
        w_V_68_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_69_out_ap_vld = 1'b1;
    end else begin
        w_V_69_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_70_out_ap_vld = 1'b1;
    end else begin
        w_V_70_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_71_out_ap_vld = 1'b1;
    end else begin
        w_V_71_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_72_out_ap_vld = 1'b1;
    end else begin
        w_V_72_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_73_out_ap_vld = 1'b1;
    end else begin
        w_V_73_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_74_out_ap_vld = 1'b1;
    end else begin
        w_V_74_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_75_out_ap_vld = 1'b1;
    end else begin
        w_V_75_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_76_out_ap_vld = 1'b1;
    end else begin
        w_V_76_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_77_out_ap_vld = 1'b1;
    end else begin
        w_V_77_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_78_out_ap_vld = 1'b1;
    end else begin
        w_V_78_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_79_out_ap_vld = 1'b1;
    end else begin
        w_V_79_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_924_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        w_V_80_out_ap_vld = 1'b1;
    end else begin
        w_V_80_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln186_1_fu_1748_p2 = (tmp_3_fu_1614_p66 + ret_V_28_fu_1608_p2);

assign add_ln186_fu_1754_p2 = (ret_V_fu_1270_p2 + tmp_1_fu_1276_p66);

assign add_ln21_fu_2006_p2 = (ap_sig_allocacmp_i + 7'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln21_fu_924_p2 = ((ap_sig_allocacmp_i == 7'd64) ? 1'b1 : 1'b0);

assign r_V_2_fu_1544_p4 = {{tmp_2_fu_1410_p66[31:7]}};

assign r_V_3_fu_1566_p4 = {{tmp_2_fu_1410_p66[31:18]}};

assign r_V_5_fu_1250_p4 = {{tmp_fu_1072_p66[31:10]}};

assign r_V_6_fu_1588_p4 = {{tmp_2_fu_1410_p66[31:3]}};

assign r_V_fu_1206_p4 = {{tmp_fu_1072_p66[31:17]}};

assign r_V_s_fu_1228_p4 = {{tmp_fu_1072_p66[31:19]}};

assign ret_V_28_fu_1608_p2 = (xor_ln1499_2_fu_1602_p2 ^ ret_V_31_fu_1558_p3);

assign ret_V_29_fu_1220_p3 = {{trunc_ln1669_6_fu_1216_p1}, {r_V_fu_1206_p4}};

assign ret_V_30_fu_1242_p3 = {{trunc_ln1669_7_fu_1238_p1}, {r_V_s_fu_1228_p4}};

assign ret_V_31_fu_1558_p3 = {{trunc_ln1669_8_fu_1554_p1}, {r_V_2_fu_1544_p4}};

assign ret_V_32_fu_1580_p3 = {{trunc_ln1669_9_fu_1576_p1}, {r_V_3_fu_1566_p4}};

assign ret_V_fu_1270_p2 = (xor_ln1499_fu_1264_p2 ^ ret_V_30_fu_1242_p3);

assign trunc_ln1669_6_fu_1216_p1 = tmp_fu_1072_p66[16:0];

assign trunc_ln1669_7_fu_1238_p1 = tmp_fu_1072_p66[18:0];

assign trunc_ln1669_8_fu_1554_p1 = tmp_2_fu_1410_p66[6:0];

assign trunc_ln1669_9_fu_1576_p1 = tmp_2_fu_1410_p66[17:0];

assign trunc_ln1669_fu_1068_p1 = ap_sig_allocacmp_i[5:0];

assign w_V_33_out = w_V_fu_292;

assign w_V_34_out = w_V_1_fu_296;

assign w_V_35_out = w_V_2_fu_300;

assign w_V_36_out = w_V_3_fu_304;

assign w_V_37_out = w_V_4_fu_308;

assign w_V_38_out = w_V_5_fu_312;

assign w_V_39_out = w_V_6_fu_316;

assign w_V_40_out = w_V_7_fu_320;

assign w_V_41_out = w_V_8_fu_324;

assign w_V_42_out = w_V_9_fu_328;

assign w_V_43_out = w_V_10_fu_332;

assign w_V_44_out = w_V_11_fu_336;

assign w_V_45_out = w_V_12_fu_340;

assign w_V_46_out = w_V_13_fu_344;

assign w_V_47_out = w_V_14_fu_348;

assign w_V_48_fu_1760_p2 = (add_ln186_fu_1754_p2 + add_ln186_1_fu_1748_p2);

assign w_V_48_out = w_V_15_fu_352;

assign w_V_49_out = w_V_16_fu_356;

assign w_V_50_out = w_V_17_fu_360;

assign w_V_51_out = w_V_18_fu_364;

assign w_V_52_out = w_V_19_fu_368;

assign w_V_53_out = w_V_20_fu_372;

assign w_V_54_out = w_V_21_fu_376;

assign w_V_55_out = w_V_22_fu_380;

assign w_V_56_out = w_V_23_fu_384;

assign w_V_57_out = w_V_24_fu_388;

assign w_V_58_out = w_V_25_fu_392;

assign w_V_59_out = w_V_26_fu_396;

assign w_V_60_out = w_V_27_fu_400;

assign w_V_61_out = w_V_28_fu_404;

assign w_V_62_out = w_V_29_fu_408;

assign w_V_63_out = w_V_30_fu_412;

assign w_V_64_out = w_V_31_fu_416;

assign w_V_65_out = w_V_32_fu_420;

assign w_V_66_out = w_V_33_fu_424;

assign w_V_67_out = w_V_34_fu_428;

assign w_V_68_out = w_V_35_fu_432;

assign w_V_69_out = w_V_36_fu_436;

assign w_V_70_out = w_V_37_fu_440;

assign w_V_71_out = w_V_38_fu_444;

assign w_V_72_out = w_V_39_fu_448;

assign w_V_73_out = w_V_40_fu_452;

assign w_V_74_out = w_V_41_fu_456;

assign w_V_75_out = w_V_42_fu_460;

assign w_V_76_out = w_V_43_fu_464;

assign w_V_77_out = w_V_44_fu_468;

assign w_V_78_out = w_V_45_fu_472;

assign w_V_79_out = w_V_46_fu_476;

assign w_V_80_out = w_V_47_fu_480;

assign xor_ln1499_2_fu_1602_p2 = (zext_ln1669_1_fu_1598_p1 ^ ret_V_32_fu_1580_p3);

assign xor_ln1499_fu_1264_p2 = (zext_ln1669_fu_1260_p1 ^ ret_V_29_fu_1220_p3);

assign zext_ln1669_1_fu_1598_p1 = r_V_6_fu_1588_p4;

assign zext_ln1669_fu_1260_p1 = r_V_5_fu_1250_p4;

endmodule //sha256_acc_sha256_acc_Pipeline_VITIS_LOOP_21_2
