-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sha256_acc is
generic (
    C_S_AXI_CONTROL_BUS_ADDR_WIDTH : INTEGER := 4;
    C_S_AXI_CONTROL_BUS_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_stream_TVALID : IN STD_LOGIC;
    in_stream_TREADY : OUT STD_LOGIC;
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_stream_TVALID : OUT STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC;
    out_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_CONTROL_BUS_AWVALID : IN STD_LOGIC;
    s_axi_CONTROL_BUS_AWREADY : OUT STD_LOGIC;
    s_axi_CONTROL_BUS_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_BUS_ADDR_WIDTH-1 downto 0);
    s_axi_CONTROL_BUS_WVALID : IN STD_LOGIC;
    s_axi_CONTROL_BUS_WREADY : OUT STD_LOGIC;
    s_axi_CONTROL_BUS_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_BUS_DATA_WIDTH-1 downto 0);
    s_axi_CONTROL_BUS_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_BUS_DATA_WIDTH/8-1 downto 0);
    s_axi_CONTROL_BUS_ARVALID : IN STD_LOGIC;
    s_axi_CONTROL_BUS_ARREADY : OUT STD_LOGIC;
    s_axi_CONTROL_BUS_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_BUS_ADDR_WIDTH-1 downto 0);
    s_axi_CONTROL_BUS_RVALID : OUT STD_LOGIC;
    s_axi_CONTROL_BUS_RREADY : IN STD_LOGIC;
    s_axi_CONTROL_BUS_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_BUS_DATA_WIDTH-1 downto 0);
    s_axi_CONTROL_BUS_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_CONTROL_BUS_BVALID : OUT STD_LOGIC;
    s_axi_CONTROL_BUS_BREADY : IN STD_LOGIC;
    s_axi_CONTROL_BUS_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of sha256_acc is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "sha256_acc_sha256_acc,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=15.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=10.059000,HLS_SYN_LAT=222,HLS_SYN_TPT=none,HLS_SYN_MEM=1,HLS_SYN_DSP=0,HLS_SYN_FF=2587,HLS_SYN_LUT=3116,HLS_VERSION=2022_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (13 downto 0) := "00000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (13 downto 0) := "00000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (13 downto 0) := "00000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (13 downto 0) := "00000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (13 downto 0) := "00000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (13 downto 0) := "00000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (13 downto 0) := "00001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (13 downto 0) := "00010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (13 downto 0) := "00100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (13 downto 0) := "01000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (13 downto 0) := "10000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv64_2 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000010";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv64_3 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000011";
    constant ap_const_lv64_4 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000100";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv64_5 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000101";
    constant ap_const_lv64_6 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000110";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv64_7 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000111";
    constant ap_const_lv32_6A09E667 : STD_LOGIC_VECTOR (31 downto 0) := "01101010000010011110011001100111";
    constant ap_const_lv32_BB67AE85 : STD_LOGIC_VECTOR (31 downto 0) := "10111011011001111010111010000101";
    constant ap_const_lv32_3C6EF372 : STD_LOGIC_VECTOR (31 downto 0) := "00111100011011101111001101110010";
    constant ap_const_lv32_A54FF53A : STD_LOGIC_VECTOR (31 downto 0) := "10100101010011111111010100111010";
    constant ap_const_lv32_510E527F : STD_LOGIC_VECTOR (31 downto 0) := "01010001000011100101001001111111";
    constant ap_const_lv32_9B05688C : STD_LOGIC_VECTOR (31 downto 0) := "10011011000001010110100010001100";
    constant ap_const_lv32_1F83D9AB : STD_LOGIC_VECTOR (31 downto 0) := "00011111100000111101100110101011";
    constant ap_const_lv32_5BE0CD19 : STD_LOGIC_VECTOR (31 downto 0) := "01011011111000001100110100011001";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal res_V_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal res_V_ce0 : STD_LOGIC;
    signal res_V_we0 : STD_LOGIC;
    signal res_V_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_V_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_V_address1 : STD_LOGIC_VECTOR (2 downto 0);
    signal res_V_ce1 : STD_LOGIC;
    signal res_V_we1 : STD_LOGIC;
    signal res_V_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_ap_start : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_ap_done : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_ap_idle : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_ap_ready : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_in_stream_TREADY : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_15_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_15_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_14_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_14_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_13_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_13_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_12_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_12_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_11_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_11_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_10_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_10_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_9_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_9_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_8_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_8_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_7_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_7_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_6_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_6_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_5_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_5_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_4_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_4_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_3_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_3_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_2_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_2_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_1_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_1_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_ap_start : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_ap_done : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_ap_idle : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_ap_ready : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_80_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_80_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_79_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_79_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_78_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_78_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_77_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_77_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_76_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_76_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_75_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_75_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_74_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_74_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_73_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_73_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_72_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_72_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_71_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_71_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_70_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_70_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_69_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_69_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_68_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_68_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_67_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_67_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_66_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_66_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_65_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_65_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_64_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_64_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_63_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_63_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_62_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_62_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_61_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_61_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_60_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_60_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_59_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_59_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_58_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_58_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_57_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_57_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_56_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_56_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_55_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_55_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_54_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_54_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_53_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_53_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_52_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_52_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_51_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_51_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_50_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_50_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_49_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_49_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_48_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_48_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_47_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_47_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_46_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_46_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_45_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_45_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_44_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_44_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_43_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_43_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_42_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_42_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_41_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_41_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_40_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_40_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_39_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_39_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_38_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_38_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_37_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_37_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_36_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_36_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_35_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_35_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_34_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_34_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_33_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_33_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_ap_start : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_ap_done : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_ap_idle : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_ap_ready : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_h_val_V_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_h_val_V_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_g_V_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_g_V_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_f_V_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_f_V_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_e_V_2_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_e_V_2_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_d_V_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_d_V_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_c_V_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_c_V_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_b_V_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_b_V_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_a_V_2_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_a_V_2_out_ap_vld : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_ap_start : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_ap_done : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_ap_idle : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_ap_ready : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_out_stream_TREADY : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_res_V_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_res_V_ce0 : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_out_stream_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_out_stream_TVALID : STD_LOGIC;
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_out_stream_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_out_stream_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_out_stream_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal add_ln186_3_fu_892_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln186_4_fu_899_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln186_5_fu_912_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln186_6_fu_919_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln186_7_fu_932_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln186_fu_939_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln186_8_fu_952_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln186_9_fu_959_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal regslice_both_out_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal regslice_both_in_stream_U_apdone_blk : STD_LOGIC;
    signal in_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal in_stream_TVALID_int_regslice : STD_LOGIC;
    signal in_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_in_stream_U_ack_in : STD_LOGIC;
    signal out_stream_TVALID_int_regslice : STD_LOGIC;
    signal out_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_out_stream_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component sha256_acc_sha256_acc_Pipeline_VITIS_LOOP_15_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_stream_TVALID : IN STD_LOGIC;
        in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        in_stream_TREADY : OUT STD_LOGIC;
        w_V_15_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_15_out_ap_vld : OUT STD_LOGIC;
        w_V_14_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_14_out_ap_vld : OUT STD_LOGIC;
        w_V_13_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_13_out_ap_vld : OUT STD_LOGIC;
        w_V_12_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_12_out_ap_vld : OUT STD_LOGIC;
        w_V_11_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_11_out_ap_vld : OUT STD_LOGIC;
        w_V_10_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_10_out_ap_vld : OUT STD_LOGIC;
        w_V_9_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_9_out_ap_vld : OUT STD_LOGIC;
        w_V_8_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_8_out_ap_vld : OUT STD_LOGIC;
        w_V_7_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_7_out_ap_vld : OUT STD_LOGIC;
        w_V_6_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_6_out_ap_vld : OUT STD_LOGIC;
        w_V_5_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_5_out_ap_vld : OUT STD_LOGIC;
        w_V_4_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_4_out_ap_vld : OUT STD_LOGIC;
        w_V_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_3_out_ap_vld : OUT STD_LOGIC;
        w_V_2_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_2_out_ap_vld : OUT STD_LOGIC;
        w_V_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_1_out_ap_vld : OUT STD_LOGIC;
        w_V_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_out_ap_vld : OUT STD_LOGIC );
    end component;


    component sha256_acc_sha256_acc_Pipeline_VITIS_LOOP_21_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        w_V_14_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_15_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_9_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_10_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_11_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_12_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_13_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_1_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_2_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_4_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_5_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_6_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_7_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_8_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_80_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_80_out_ap_vld : OUT STD_LOGIC;
        w_V_79_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_79_out_ap_vld : OUT STD_LOGIC;
        w_V_78_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_78_out_ap_vld : OUT STD_LOGIC;
        w_V_77_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_77_out_ap_vld : OUT STD_LOGIC;
        w_V_76_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_76_out_ap_vld : OUT STD_LOGIC;
        w_V_75_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_75_out_ap_vld : OUT STD_LOGIC;
        w_V_74_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_74_out_ap_vld : OUT STD_LOGIC;
        w_V_73_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_73_out_ap_vld : OUT STD_LOGIC;
        w_V_72_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_72_out_ap_vld : OUT STD_LOGIC;
        w_V_71_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_71_out_ap_vld : OUT STD_LOGIC;
        w_V_70_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_70_out_ap_vld : OUT STD_LOGIC;
        w_V_69_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_69_out_ap_vld : OUT STD_LOGIC;
        w_V_68_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_68_out_ap_vld : OUT STD_LOGIC;
        w_V_67_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_67_out_ap_vld : OUT STD_LOGIC;
        w_V_66_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_66_out_ap_vld : OUT STD_LOGIC;
        w_V_65_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_65_out_ap_vld : OUT STD_LOGIC;
        w_V_64_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_64_out_ap_vld : OUT STD_LOGIC;
        w_V_63_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_63_out_ap_vld : OUT STD_LOGIC;
        w_V_62_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_62_out_ap_vld : OUT STD_LOGIC;
        w_V_61_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_61_out_ap_vld : OUT STD_LOGIC;
        w_V_60_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_60_out_ap_vld : OUT STD_LOGIC;
        w_V_59_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_59_out_ap_vld : OUT STD_LOGIC;
        w_V_58_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_58_out_ap_vld : OUT STD_LOGIC;
        w_V_57_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_57_out_ap_vld : OUT STD_LOGIC;
        w_V_56_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_56_out_ap_vld : OUT STD_LOGIC;
        w_V_55_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_55_out_ap_vld : OUT STD_LOGIC;
        w_V_54_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_54_out_ap_vld : OUT STD_LOGIC;
        w_V_53_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_53_out_ap_vld : OUT STD_LOGIC;
        w_V_52_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_52_out_ap_vld : OUT STD_LOGIC;
        w_V_51_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_51_out_ap_vld : OUT STD_LOGIC;
        w_V_50_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_50_out_ap_vld : OUT STD_LOGIC;
        w_V_49_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_49_out_ap_vld : OUT STD_LOGIC;
        w_V_48_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_48_out_ap_vld : OUT STD_LOGIC;
        w_V_47_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_47_out_ap_vld : OUT STD_LOGIC;
        w_V_46_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_46_out_ap_vld : OUT STD_LOGIC;
        w_V_45_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_45_out_ap_vld : OUT STD_LOGIC;
        w_V_44_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_44_out_ap_vld : OUT STD_LOGIC;
        w_V_43_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_43_out_ap_vld : OUT STD_LOGIC;
        w_V_42_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_42_out_ap_vld : OUT STD_LOGIC;
        w_V_41_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_41_out_ap_vld : OUT STD_LOGIC;
        w_V_40_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_40_out_ap_vld : OUT STD_LOGIC;
        w_V_39_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_39_out_ap_vld : OUT STD_LOGIC;
        w_V_38_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_38_out_ap_vld : OUT STD_LOGIC;
        w_V_37_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_37_out_ap_vld : OUT STD_LOGIC;
        w_V_36_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_36_out_ap_vld : OUT STD_LOGIC;
        w_V_35_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_35_out_ap_vld : OUT STD_LOGIC;
        w_V_34_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_34_out_ap_vld : OUT STD_LOGIC;
        w_V_33_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        w_V_33_out_ap_vld : OUT STD_LOGIC );
    end component;


    component sha256_acc_sha256_acc_Pipeline_VITIS_LOOP_30_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        w_V_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_1_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_2_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_4_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_5_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_6_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_7_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_8_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_9_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_10_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_11_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_12_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_13_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_14_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_15_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_33_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_34_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_35_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_36_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_37_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_38_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_39_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_40_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_41_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_42_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_43_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_44_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_45_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_46_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_47_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_48_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_49_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_50_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_51_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_52_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_53_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_54_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_55_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_56_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_57_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_58_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_59_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_60_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_61_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_62_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_63_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_64_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_65_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_66_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_67_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_68_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_69_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_70_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_71_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_72_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_73_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_74_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_75_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_76_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_77_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_78_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_79_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        w_V_80_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        h_val_V_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        h_val_V_out_ap_vld : OUT STD_LOGIC;
        g_V_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        g_V_out_ap_vld : OUT STD_LOGIC;
        f_V_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        f_V_out_ap_vld : OUT STD_LOGIC;
        e_V_2_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        e_V_2_out_ap_vld : OUT STD_LOGIC;
        d_V_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        d_V_out_ap_vld : OUT STD_LOGIC;
        c_V_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        c_V_out_ap_vld : OUT STD_LOGIC;
        b_V_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        b_V_out_ap_vld : OUT STD_LOGIC;
        a_V_2_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        a_V_2_out_ap_vld : OUT STD_LOGIC );
    end component;


    component sha256_acc_sha256_acc_Pipeline_VITIS_LOOP_40_4 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        out_stream_TREADY : IN STD_LOGIC;
        res_V_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        res_V_ce0 : OUT STD_LOGIC;
        res_V_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_stream_TVALID : OUT STD_LOGIC;
        out_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component sha256_acc_res_V_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component sha256_acc_CONTROL_BUS_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component sha256_acc_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    res_V_U : component sha256_acc_res_V_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => res_V_address0,
        ce0 => res_V_ce0,
        we0 => res_V_we0,
        d0 => res_V_d0,
        q0 => res_V_q0,
        address1 => res_V_address1,
        ce1 => res_V_ce1,
        we1 => res_V_we1,
        d1 => res_V_d1);

    grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449 : component sha256_acc_sha256_acc_Pipeline_VITIS_LOOP_15_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_ap_start,
        ap_done => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_ap_done,
        ap_idle => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_ap_idle,
        ap_ready => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_ap_ready,
        in_stream_TVALID => in_stream_TVALID_int_regslice,
        in_stream_TDATA => in_stream_TDATA_int_regslice,
        in_stream_TREADY => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_in_stream_TREADY,
        w_V_15_out => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_15_out,
        w_V_15_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_15_out_ap_vld,
        w_V_14_out => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_14_out,
        w_V_14_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_14_out_ap_vld,
        w_V_13_out => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_13_out,
        w_V_13_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_13_out_ap_vld,
        w_V_12_out => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_12_out,
        w_V_12_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_12_out_ap_vld,
        w_V_11_out => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_11_out,
        w_V_11_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_11_out_ap_vld,
        w_V_10_out => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_10_out,
        w_V_10_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_10_out_ap_vld,
        w_V_9_out => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_9_out,
        w_V_9_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_9_out_ap_vld,
        w_V_8_out => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_8_out,
        w_V_8_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_8_out_ap_vld,
        w_V_7_out => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_7_out,
        w_V_7_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_7_out_ap_vld,
        w_V_6_out => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_6_out,
        w_V_6_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_6_out_ap_vld,
        w_V_5_out => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_5_out,
        w_V_5_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_5_out_ap_vld,
        w_V_4_out => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_4_out,
        w_V_4_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_4_out_ap_vld,
        w_V_3_out => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_3_out,
        w_V_3_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_3_out_ap_vld,
        w_V_2_out => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_2_out,
        w_V_2_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_2_out_ap_vld,
        w_V_1_out => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_1_out,
        w_V_1_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_1_out_ap_vld,
        w_V_out => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_out,
        w_V_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_out_ap_vld);

    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471 : component sha256_acc_sha256_acc_Pipeline_VITIS_LOOP_21_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_ap_start,
        ap_done => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_ap_done,
        ap_idle => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_ap_idle,
        ap_ready => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_ap_ready,
        w_V_14_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_14_out,
        w_V_15_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_15_out,
        w_V_9_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_9_out,
        w_V_10_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_10_out,
        w_V_11_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_11_out,
        w_V_12_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_12_out,
        w_V_13_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_13_out,
        w_V_1_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_1_out,
        w_V_2_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_2_out,
        w_V_3_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_3_out,
        w_V_4_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_4_out,
        w_V_5_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_5_out,
        w_V_6_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_6_out,
        w_V_7_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_7_out,
        w_V_8_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_8_out,
        w_V_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_out,
        w_V_80_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_80_out,
        w_V_80_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_80_out_ap_vld,
        w_V_79_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_79_out,
        w_V_79_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_79_out_ap_vld,
        w_V_78_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_78_out,
        w_V_78_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_78_out_ap_vld,
        w_V_77_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_77_out,
        w_V_77_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_77_out_ap_vld,
        w_V_76_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_76_out,
        w_V_76_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_76_out_ap_vld,
        w_V_75_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_75_out,
        w_V_75_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_75_out_ap_vld,
        w_V_74_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_74_out,
        w_V_74_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_74_out_ap_vld,
        w_V_73_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_73_out,
        w_V_73_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_73_out_ap_vld,
        w_V_72_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_72_out,
        w_V_72_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_72_out_ap_vld,
        w_V_71_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_71_out,
        w_V_71_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_71_out_ap_vld,
        w_V_70_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_70_out,
        w_V_70_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_70_out_ap_vld,
        w_V_69_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_69_out,
        w_V_69_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_69_out_ap_vld,
        w_V_68_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_68_out,
        w_V_68_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_68_out_ap_vld,
        w_V_67_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_67_out,
        w_V_67_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_67_out_ap_vld,
        w_V_66_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_66_out,
        w_V_66_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_66_out_ap_vld,
        w_V_65_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_65_out,
        w_V_65_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_65_out_ap_vld,
        w_V_64_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_64_out,
        w_V_64_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_64_out_ap_vld,
        w_V_63_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_63_out,
        w_V_63_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_63_out_ap_vld,
        w_V_62_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_62_out,
        w_V_62_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_62_out_ap_vld,
        w_V_61_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_61_out,
        w_V_61_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_61_out_ap_vld,
        w_V_60_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_60_out,
        w_V_60_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_60_out_ap_vld,
        w_V_59_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_59_out,
        w_V_59_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_59_out_ap_vld,
        w_V_58_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_58_out,
        w_V_58_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_58_out_ap_vld,
        w_V_57_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_57_out,
        w_V_57_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_57_out_ap_vld,
        w_V_56_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_56_out,
        w_V_56_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_56_out_ap_vld,
        w_V_55_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_55_out,
        w_V_55_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_55_out_ap_vld,
        w_V_54_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_54_out,
        w_V_54_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_54_out_ap_vld,
        w_V_53_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_53_out,
        w_V_53_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_53_out_ap_vld,
        w_V_52_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_52_out,
        w_V_52_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_52_out_ap_vld,
        w_V_51_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_51_out,
        w_V_51_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_51_out_ap_vld,
        w_V_50_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_50_out,
        w_V_50_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_50_out_ap_vld,
        w_V_49_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_49_out,
        w_V_49_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_49_out_ap_vld,
        w_V_48_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_48_out,
        w_V_48_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_48_out_ap_vld,
        w_V_47_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_47_out,
        w_V_47_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_47_out_ap_vld,
        w_V_46_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_46_out,
        w_V_46_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_46_out_ap_vld,
        w_V_45_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_45_out,
        w_V_45_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_45_out_ap_vld,
        w_V_44_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_44_out,
        w_V_44_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_44_out_ap_vld,
        w_V_43_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_43_out,
        w_V_43_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_43_out_ap_vld,
        w_V_42_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_42_out,
        w_V_42_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_42_out_ap_vld,
        w_V_41_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_41_out,
        w_V_41_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_41_out_ap_vld,
        w_V_40_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_40_out,
        w_V_40_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_40_out_ap_vld,
        w_V_39_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_39_out,
        w_V_39_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_39_out_ap_vld,
        w_V_38_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_38_out,
        w_V_38_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_38_out_ap_vld,
        w_V_37_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_37_out,
        w_V_37_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_37_out_ap_vld,
        w_V_36_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_36_out,
        w_V_36_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_36_out_ap_vld,
        w_V_35_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_35_out,
        w_V_35_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_35_out_ap_vld,
        w_V_34_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_34_out,
        w_V_34_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_34_out_ap_vld,
        w_V_33_out => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_33_out,
        w_V_33_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_33_out_ap_vld);

    grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539 : component sha256_acc_sha256_acc_Pipeline_VITIS_LOOP_30_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_ap_start,
        ap_done => grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_ap_done,
        ap_idle => grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_ap_idle,
        ap_ready => grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_ap_ready,
        w_V_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_out,
        w_V_1_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_1_out,
        w_V_2_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_2_out,
        w_V_3_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_3_out,
        w_V_4_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_4_out,
        w_V_5_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_5_out,
        w_V_6_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_6_out,
        w_V_7_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_7_out,
        w_V_8_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_8_out,
        w_V_9_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_9_out,
        w_V_10_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_10_out,
        w_V_11_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_11_out,
        w_V_12_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_12_out,
        w_V_13_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_13_out,
        w_V_14_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_14_out,
        w_V_15_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_15_out,
        w_V_33_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_33_out,
        w_V_34_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_34_out,
        w_V_35_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_35_out,
        w_V_36_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_36_out,
        w_V_37_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_37_out,
        w_V_38_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_38_out,
        w_V_39_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_39_out,
        w_V_40_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_40_out,
        w_V_41_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_41_out,
        w_V_42_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_42_out,
        w_V_43_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_43_out,
        w_V_44_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_44_out,
        w_V_45_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_45_out,
        w_V_46_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_46_out,
        w_V_47_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_47_out,
        w_V_48_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_48_out,
        w_V_49_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_49_out,
        w_V_50_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_50_out,
        w_V_51_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_51_out,
        w_V_52_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_52_out,
        w_V_53_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_53_out,
        w_V_54_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_54_out,
        w_V_55_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_55_out,
        w_V_56_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_56_out,
        w_V_57_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_57_out,
        w_V_58_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_58_out,
        w_V_59_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_59_out,
        w_V_60_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_60_out,
        w_V_61_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_61_out,
        w_V_62_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_62_out,
        w_V_63_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_63_out,
        w_V_64_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_64_out,
        w_V_65_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_65_out,
        w_V_66_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_66_out,
        w_V_67_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_67_out,
        w_V_68_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_68_out,
        w_V_69_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_69_out,
        w_V_70_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_70_out,
        w_V_71_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_71_out,
        w_V_72_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_72_out,
        w_V_73_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_73_out,
        w_V_74_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_74_out,
        w_V_75_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_75_out,
        w_V_76_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_76_out,
        w_V_77_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_77_out,
        w_V_78_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_78_out,
        w_V_79_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_79_out,
        w_V_80_reload => grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_80_out,
        h_val_V_out => grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_h_val_V_out,
        h_val_V_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_h_val_V_out_ap_vld,
        g_V_out => grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_g_V_out,
        g_V_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_g_V_out_ap_vld,
        f_V_out => grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_f_V_out,
        f_V_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_f_V_out_ap_vld,
        e_V_2_out => grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_e_V_2_out,
        e_V_2_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_e_V_2_out_ap_vld,
        d_V_out => grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_d_V_out,
        d_V_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_d_V_out_ap_vld,
        c_V_out => grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_c_V_out,
        c_V_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_c_V_out_ap_vld,
        b_V_out => grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_b_V_out,
        b_V_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_b_V_out_ap_vld,
        a_V_2_out => grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_a_V_2_out,
        a_V_2_out_ap_vld => grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_a_V_2_out_ap_vld);

    grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617 : component sha256_acc_sha256_acc_Pipeline_VITIS_LOOP_40_4
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_ap_start,
        ap_done => grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_ap_done,
        ap_idle => grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_ap_idle,
        ap_ready => grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_ap_ready,
        out_stream_TREADY => grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_out_stream_TREADY,
        res_V_address0 => grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_res_V_address0,
        res_V_ce0 => grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_res_V_ce0,
        res_V_q0 => res_V_q0,
        out_stream_TDATA => grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_out_stream_TDATA,
        out_stream_TVALID => grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_out_stream_TVALID,
        out_stream_TKEEP => grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_out_stream_TKEEP,
        out_stream_TSTRB => grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_out_stream_TSTRB,
        out_stream_TLAST => grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_out_stream_TLAST);

    CONTROL_BUS_s_axi_U : component sha256_acc_CONTROL_BUS_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_BUS_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_BUS_DATA_WIDTH)
    port map (
        AWVALID => s_axi_CONTROL_BUS_AWVALID,
        AWREADY => s_axi_CONTROL_BUS_AWREADY,
        AWADDR => s_axi_CONTROL_BUS_AWADDR,
        WVALID => s_axi_CONTROL_BUS_WVALID,
        WREADY => s_axi_CONTROL_BUS_WREADY,
        WDATA => s_axi_CONTROL_BUS_WDATA,
        WSTRB => s_axi_CONTROL_BUS_WSTRB,
        ARVALID => s_axi_CONTROL_BUS_ARVALID,
        ARREADY => s_axi_CONTROL_BUS_ARREADY,
        ARADDR => s_axi_CONTROL_BUS_ARADDR,
        RVALID => s_axi_CONTROL_BUS_RVALID,
        RREADY => s_axi_CONTROL_BUS_RREADY,
        RDATA => s_axi_CONTROL_BUS_RDATA,
        RRESP => s_axi_CONTROL_BUS_RRESP,
        BVALID => s_axi_CONTROL_BUS_BVALID,
        BREADY => s_axi_CONTROL_BUS_BREADY,
        BRESP => s_axi_CONTROL_BUS_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    regslice_both_in_stream_U : component sha256_acc_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TDATA,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_U_ack_in,
        data_out => in_stream_TDATA_int_regslice,
        vld_out => in_stream_TVALID_int_regslice,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_U_apdone_blk);

    regslice_both_out_stream_V_data_V_U : component sha256_acc_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_out_stream_TDATA,
        vld_in => grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_out_stream_TVALID,
        ack_in => out_stream_TREADY_int_regslice,
        data_out => out_stream_TDATA,
        vld_out => regslice_both_out_stream_V_data_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_data_V_U_apdone_blk);

    regslice_both_out_stream_V_keep_V_U : component sha256_acc_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_out_stream_TKEEP,
        vld_in => grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_keep_V_U_ack_in_dummy,
        data_out => out_stream_TKEEP,
        vld_out => regslice_both_out_stream_V_keep_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_keep_V_U_apdone_blk);

    regslice_both_out_stream_V_strb_V_U : component sha256_acc_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_out_stream_TSTRB,
        vld_in => grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_strb_V_U_ack_in_dummy,
        data_out => out_stream_TSTRB,
        vld_out => regslice_both_out_stream_V_strb_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_strb_V_U_apdone_blk);

    regslice_both_out_stream_V_last_V_U : component sha256_acc_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_out_stream_TLAST,
        vld_in => grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_last_V_U_ack_in_dummy,
        data_out => out_stream_TLAST,
        vld_out => regslice_both_out_stream_V_last_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_ap_ready = ap_const_logic_1)) then 
                    grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_ap_ready = ap_const_logic_1)) then 
                    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                    grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_ap_ready = ap_const_logic_1)) then 
                    grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
                    grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_ap_ready = ap_const_logic_1)) then 
                    grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_ap_done, grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_ap_done, grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_ap_done, grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_ap_done, ap_CS_fsm_state3, ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state13, ap_CS_fsm_state14, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                if (((grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then
                    ap_NS_fsm <= ap_ST_fsm_state14;
                else
                    ap_NS_fsm <= ap_ST_fsm_state13;
                end if;
            when ap_ST_fsm_state14 => 
                if (((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state14))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state14;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln186_3_fu_892_p2 <= std_logic_vector(unsigned(grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_a_V_2_out) + unsigned(ap_const_lv32_6A09E667));
    add_ln186_4_fu_899_p2 <= std_logic_vector(unsigned(grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_b_V_out) + unsigned(ap_const_lv32_BB67AE85));
    add_ln186_5_fu_912_p2 <= std_logic_vector(unsigned(grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_c_V_out) + unsigned(ap_const_lv32_3C6EF372));
    add_ln186_6_fu_919_p2 <= std_logic_vector(unsigned(grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_d_V_out) + unsigned(ap_const_lv32_A54FF53A));
    add_ln186_7_fu_932_p2 <= std_logic_vector(unsigned(grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_e_V_2_out) + unsigned(ap_const_lv32_510E527F));
    add_ln186_8_fu_952_p2 <= std_logic_vector(unsigned(grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_g_V_out) + unsigned(ap_const_lv32_1F83D9AB));
    add_ln186_9_fu_959_p2 <= std_logic_vector(unsigned(grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_h_val_V_out) + unsigned(ap_const_lv32_5BE0CD19));
    add_ln186_fu_939_p2 <= std_logic_vector(unsigned(grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_f_V_out) + unsigned(ap_const_lv32_9B05688C));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;

    ap_ST_fsm_state13_blk_assign_proc : process(grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_ap_done)
    begin
        if ((grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state13_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state13_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state14_blk_assign_proc : process(regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if ((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state14_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state14_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_ap_done)
    begin
        if ((grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_ap_done)
    begin
        if ((grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_ST_fsm_state7_blk_assign_proc : process(grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_ap_done)
    begin
        if ((grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_CS_fsm_state14, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state14))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state14, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state14))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_ap_start <= grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_ap_start_reg;
    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_ap_start <= grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_ap_start_reg;
    grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_ap_start <= grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_ap_start_reg;
    grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_ap_start <= grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_ap_start_reg;
    grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_out_stream_TREADY <= (out_stream_TREADY_int_regslice and ap_CS_fsm_state13);
    in_stream_TREADY <= regslice_both_in_stream_U_ack_in;

    in_stream_TREADY_int_regslice_assign_proc : process(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_in_stream_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_stream_TREADY_int_regslice <= grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_in_stream_TREADY;
        else 
            in_stream_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    out_stream_TVALID <= regslice_both_out_stream_V_data_V_U_vld_out;
    out_stream_TVALID_int_regslice <= grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_out_stream_TVALID;

    res_V_address0_assign_proc : process(grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_res_V_address0, ap_CS_fsm_state13, ap_CS_fsm_state8, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            res_V_address0 <= ap_const_lv64_7(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            res_V_address0 <= ap_const_lv64_5(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            res_V_address0 <= ap_const_lv64_3(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            res_V_address0 <= ap_const_lv64_1(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            res_V_address0 <= grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_res_V_address0;
        else 
            res_V_address0 <= "XXX";
        end if; 
    end process;


    res_V_address1_assign_proc : process(ap_CS_fsm_state8, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            res_V_address1 <= ap_const_lv64_6(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            res_V_address1 <= ap_const_lv64_4(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            res_V_address1 <= ap_const_lv64_2(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            res_V_address1 <= ap_const_lv64_0(3 - 1 downto 0);
        else 
            res_V_address1 <= "XXX";
        end if; 
    end process;


    res_V_ce0_assign_proc : process(grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_res_V_ce0, ap_CS_fsm_state13, ap_CS_fsm_state8, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            res_V_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            res_V_ce0 <= grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_res_V_ce0;
        else 
            res_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    res_V_ce1_assign_proc : process(ap_CS_fsm_state8, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            res_V_ce1 <= ap_const_logic_1;
        else 
            res_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    res_V_d0_assign_proc : process(ap_CS_fsm_state8, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11, add_ln186_4_fu_899_p2, add_ln186_6_fu_919_p2, add_ln186_fu_939_p2, add_ln186_9_fu_959_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            res_V_d0 <= add_ln186_9_fu_959_p2;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            res_V_d0 <= add_ln186_fu_939_p2;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            res_V_d0 <= add_ln186_6_fu_919_p2;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            res_V_d0 <= add_ln186_4_fu_899_p2;
        else 
            res_V_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    res_V_d1_assign_proc : process(ap_CS_fsm_state8, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11, add_ln186_3_fu_892_p2, add_ln186_5_fu_912_p2, add_ln186_7_fu_932_p2, add_ln186_8_fu_952_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            res_V_d1 <= add_ln186_8_fu_952_p2;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            res_V_d1 <= add_ln186_7_fu_932_p2;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            res_V_d1 <= add_ln186_5_fu_912_p2;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            res_V_d1 <= add_ln186_3_fu_892_p2;
        else 
            res_V_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    res_V_we0_assign_proc : process(ap_CS_fsm_state8, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            res_V_we0 <= ap_const_logic_1;
        else 
            res_V_we0 <= ap_const_logic_0;
        end if; 
    end process;


    res_V_we1_assign_proc : process(ap_CS_fsm_state8, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            res_V_we1 <= ap_const_logic_1;
        else 
            res_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

end behav;
