// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="sha256_acc_sha256_acc,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=15.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=10.059000,HLS_SYN_LAT=222,HLS_SYN_TPT=none,HLS_SYN_MEM=1,HLS_SYN_DSP=0,HLS_SYN_FF=2587,HLS_SYN_LUT=3116,HLS_VERSION=2022_2}" *)

module sha256_acc (
        ap_clk,
        ap_rst_n,
        in_stream_TDATA,
        in_stream_TVALID,
        in_stream_TREADY,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TREADY,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TLAST,
        s_axi_CONTROL_BUS_AWVALID,
        s_axi_CONTROL_BUS_AWREADY,
        s_axi_CONTROL_BUS_AWADDR,
        s_axi_CONTROL_BUS_WVALID,
        s_axi_CONTROL_BUS_WREADY,
        s_axi_CONTROL_BUS_WDATA,
        s_axi_CONTROL_BUS_WSTRB,
        s_axi_CONTROL_BUS_ARVALID,
        s_axi_CONTROL_BUS_ARREADY,
        s_axi_CONTROL_BUS_ARADDR,
        s_axi_CONTROL_BUS_RVALID,
        s_axi_CONTROL_BUS_RREADY,
        s_axi_CONTROL_BUS_RDATA,
        s_axi_CONTROL_BUS_RRESP,
        s_axi_CONTROL_BUS_BVALID,
        s_axi_CONTROL_BUS_BREADY,
        s_axi_CONTROL_BUS_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 14'd1;
parameter    ap_ST_fsm_state2 = 14'd2;
parameter    ap_ST_fsm_state3 = 14'd4;
parameter    ap_ST_fsm_state4 = 14'd8;
parameter    ap_ST_fsm_state5 = 14'd16;
parameter    ap_ST_fsm_state6 = 14'd32;
parameter    ap_ST_fsm_state7 = 14'd64;
parameter    ap_ST_fsm_state8 = 14'd128;
parameter    ap_ST_fsm_state9 = 14'd256;
parameter    ap_ST_fsm_state10 = 14'd512;
parameter    ap_ST_fsm_state11 = 14'd1024;
parameter    ap_ST_fsm_state12 = 14'd2048;
parameter    ap_ST_fsm_state13 = 14'd4096;
parameter    ap_ST_fsm_state14 = 14'd8192;
parameter    C_S_AXI_CONTROL_BUS_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_BUS_ADDR_WIDTH = 4;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_BUS_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [31:0] in_stream_TDATA;
input   in_stream_TVALID;
output   in_stream_TREADY;
output  [31:0] out_stream_TDATA;
output   out_stream_TVALID;
input   out_stream_TREADY;
output  [3:0] out_stream_TKEEP;
output  [3:0] out_stream_TSTRB;
output  [0:0] out_stream_TLAST;
input   s_axi_CONTROL_BUS_AWVALID;
output   s_axi_CONTROL_BUS_AWREADY;
input  [C_S_AXI_CONTROL_BUS_ADDR_WIDTH - 1:0] s_axi_CONTROL_BUS_AWADDR;
input   s_axi_CONTROL_BUS_WVALID;
output   s_axi_CONTROL_BUS_WREADY;
input  [C_S_AXI_CONTROL_BUS_DATA_WIDTH - 1:0] s_axi_CONTROL_BUS_WDATA;
input  [C_S_AXI_CONTROL_BUS_WSTRB_WIDTH - 1:0] s_axi_CONTROL_BUS_WSTRB;
input   s_axi_CONTROL_BUS_ARVALID;
output   s_axi_CONTROL_BUS_ARREADY;
input  [C_S_AXI_CONTROL_BUS_ADDR_WIDTH - 1:0] s_axi_CONTROL_BUS_ARADDR;
output   s_axi_CONTROL_BUS_RVALID;
input   s_axi_CONTROL_BUS_RREADY;
output  [C_S_AXI_CONTROL_BUS_DATA_WIDTH - 1:0] s_axi_CONTROL_BUS_RDATA;
output  [1:0] s_axi_CONTROL_BUS_RRESP;
output   s_axi_CONTROL_BUS_BVALID;
input   s_axi_CONTROL_BUS_BREADY;
output  [1:0] s_axi_CONTROL_BUS_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [13:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
reg   [2:0] res_V_address0;
reg    res_V_ce0;
reg    res_V_we0;
reg   [31:0] res_V_d0;
wire   [31:0] res_V_q0;
reg   [2:0] res_V_address1;
reg    res_V_ce1;
reg    res_V_we1;
reg   [31:0] res_V_d1;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_ap_start;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_ap_done;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_ap_idle;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_ap_ready;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_in_stream_TREADY;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_15_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_15_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_14_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_14_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_13_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_13_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_12_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_12_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_11_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_11_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_10_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_10_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_9_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_9_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_8_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_8_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_7_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_7_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_6_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_6_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_5_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_5_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_4_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_4_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_3_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_3_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_2_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_2_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_1_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_1_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_out_ap_vld;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_ap_start;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_ap_done;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_ap_idle;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_ap_ready;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_80_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_80_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_79_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_79_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_78_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_78_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_77_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_77_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_76_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_76_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_75_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_75_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_74_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_74_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_73_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_73_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_72_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_72_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_71_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_71_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_70_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_70_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_69_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_69_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_68_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_68_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_67_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_67_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_66_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_66_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_65_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_65_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_64_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_64_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_63_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_63_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_62_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_62_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_61_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_61_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_60_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_60_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_59_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_59_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_58_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_58_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_57_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_57_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_56_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_56_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_55_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_55_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_54_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_54_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_53_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_53_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_52_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_52_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_51_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_51_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_50_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_50_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_49_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_49_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_48_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_48_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_47_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_47_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_46_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_46_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_45_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_45_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_44_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_44_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_43_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_43_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_42_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_42_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_41_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_41_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_40_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_40_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_39_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_39_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_38_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_38_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_37_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_37_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_36_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_36_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_35_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_35_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_34_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_34_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_33_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_33_out_ap_vld;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_ap_start;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_ap_done;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_ap_idle;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_ap_ready;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_h_val_V_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_h_val_V_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_g_V_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_g_V_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_f_V_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_f_V_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_e_V_2_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_e_V_2_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_d_V_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_d_V_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_c_V_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_c_V_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_b_V_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_b_V_out_ap_vld;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_a_V_2_out;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_a_V_2_out_ap_vld;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_ap_start;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_ap_done;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_ap_idle;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_ap_ready;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_out_stream_TREADY;
wire   [2:0] grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_res_V_address0;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_res_V_ce0;
wire   [31:0] grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_out_stream_TDATA;
wire    grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_out_stream_TVALID;
wire   [3:0] grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_out_stream_TKEEP;
wire   [3:0] grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_out_stream_TSTRB;
wire   [0:0] grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_out_stream_TLAST;
reg    grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg    grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_ap_start_reg;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
reg    grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_ap_start_reg;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
wire   [31:0] add_ln186_3_fu_892_p2;
wire   [31:0] add_ln186_4_fu_899_p2;
wire   [31:0] add_ln186_5_fu_912_p2;
wire   [31:0] add_ln186_6_fu_919_p2;
wire   [31:0] add_ln186_7_fu_932_p2;
wire   [31:0] add_ln186_fu_939_p2;
wire   [31:0] add_ln186_8_fu_952_p2;
wire   [31:0] add_ln186_9_fu_959_p2;
wire    ap_CS_fsm_state14;
wire    regslice_both_out_stream_V_data_V_U_apdone_blk;
reg   [13:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
wire    regslice_both_in_stream_U_apdone_blk;
wire   [31:0] in_stream_TDATA_int_regslice;
wire    in_stream_TVALID_int_regslice;
reg    in_stream_TREADY_int_regslice;
wire    regslice_both_in_stream_U_ack_in;
wire    out_stream_TVALID_int_regslice;
wire    out_stream_TREADY_int_regslice;
wire    regslice_both_out_stream_V_data_V_U_vld_out;
wire    regslice_both_out_stream_V_keep_V_U_apdone_blk;
wire    regslice_both_out_stream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_keep_V_U_vld_out;
wire    regslice_both_out_stream_V_strb_V_U_apdone_blk;
wire    regslice_both_out_stream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_strb_V_U_vld_out;
wire    regslice_both_out_stream_V_last_V_U_apdone_blk;
wire    regslice_both_out_stream_V_last_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 14'd1;
#0 grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_ap_start_reg = 1'b0;
#0 grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_ap_start_reg = 1'b0;
#0 grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_ap_start_reg = 1'b0;
#0 grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_ap_start_reg = 1'b0;
end

sha256_acc_res_V_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
res_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(res_V_address0),
    .ce0(res_V_ce0),
    .we0(res_V_we0),
    .d0(res_V_d0),
    .q0(res_V_q0),
    .address1(res_V_address1),
    .ce1(res_V_ce1),
    .we1(res_V_we1),
    .d1(res_V_d1)
);

sha256_acc_sha256_acc_Pipeline_VITIS_LOOP_15_1 grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_ap_start),
    .ap_done(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_ap_done),
    .ap_idle(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_ap_idle),
    .ap_ready(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_ap_ready),
    .in_stream_TVALID(in_stream_TVALID_int_regslice),
    .in_stream_TDATA(in_stream_TDATA_int_regslice),
    .in_stream_TREADY(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_in_stream_TREADY),
    .w_V_15_out(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_15_out),
    .w_V_15_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_15_out_ap_vld),
    .w_V_14_out(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_14_out),
    .w_V_14_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_14_out_ap_vld),
    .w_V_13_out(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_13_out),
    .w_V_13_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_13_out_ap_vld),
    .w_V_12_out(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_12_out),
    .w_V_12_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_12_out_ap_vld),
    .w_V_11_out(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_11_out),
    .w_V_11_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_11_out_ap_vld),
    .w_V_10_out(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_10_out),
    .w_V_10_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_10_out_ap_vld),
    .w_V_9_out(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_9_out),
    .w_V_9_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_9_out_ap_vld),
    .w_V_8_out(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_8_out),
    .w_V_8_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_8_out_ap_vld),
    .w_V_7_out(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_7_out),
    .w_V_7_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_7_out_ap_vld),
    .w_V_6_out(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_6_out),
    .w_V_6_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_6_out_ap_vld),
    .w_V_5_out(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_5_out),
    .w_V_5_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_5_out_ap_vld),
    .w_V_4_out(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_4_out),
    .w_V_4_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_4_out_ap_vld),
    .w_V_3_out(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_3_out),
    .w_V_3_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_3_out_ap_vld),
    .w_V_2_out(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_2_out),
    .w_V_2_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_2_out_ap_vld),
    .w_V_1_out(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_1_out),
    .w_V_1_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_1_out_ap_vld),
    .w_V_out(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_out),
    .w_V_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_out_ap_vld)
);

sha256_acc_sha256_acc_Pipeline_VITIS_LOOP_21_2 grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_ap_start),
    .ap_done(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_ap_done),
    .ap_idle(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_ap_idle),
    .ap_ready(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_ap_ready),
    .w_V_14_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_14_out),
    .w_V_15_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_15_out),
    .w_V_9_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_9_out),
    .w_V_10_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_10_out),
    .w_V_11_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_11_out),
    .w_V_12_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_12_out),
    .w_V_13_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_13_out),
    .w_V_1_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_1_out),
    .w_V_2_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_2_out),
    .w_V_3_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_3_out),
    .w_V_4_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_4_out),
    .w_V_5_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_5_out),
    .w_V_6_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_6_out),
    .w_V_7_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_7_out),
    .w_V_8_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_8_out),
    .w_V_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_out),
    .w_V_80_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_80_out),
    .w_V_80_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_80_out_ap_vld),
    .w_V_79_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_79_out),
    .w_V_79_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_79_out_ap_vld),
    .w_V_78_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_78_out),
    .w_V_78_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_78_out_ap_vld),
    .w_V_77_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_77_out),
    .w_V_77_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_77_out_ap_vld),
    .w_V_76_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_76_out),
    .w_V_76_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_76_out_ap_vld),
    .w_V_75_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_75_out),
    .w_V_75_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_75_out_ap_vld),
    .w_V_74_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_74_out),
    .w_V_74_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_74_out_ap_vld),
    .w_V_73_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_73_out),
    .w_V_73_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_73_out_ap_vld),
    .w_V_72_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_72_out),
    .w_V_72_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_72_out_ap_vld),
    .w_V_71_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_71_out),
    .w_V_71_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_71_out_ap_vld),
    .w_V_70_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_70_out),
    .w_V_70_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_70_out_ap_vld),
    .w_V_69_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_69_out),
    .w_V_69_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_69_out_ap_vld),
    .w_V_68_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_68_out),
    .w_V_68_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_68_out_ap_vld),
    .w_V_67_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_67_out),
    .w_V_67_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_67_out_ap_vld),
    .w_V_66_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_66_out),
    .w_V_66_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_66_out_ap_vld),
    .w_V_65_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_65_out),
    .w_V_65_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_65_out_ap_vld),
    .w_V_64_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_64_out),
    .w_V_64_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_64_out_ap_vld),
    .w_V_63_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_63_out),
    .w_V_63_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_63_out_ap_vld),
    .w_V_62_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_62_out),
    .w_V_62_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_62_out_ap_vld),
    .w_V_61_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_61_out),
    .w_V_61_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_61_out_ap_vld),
    .w_V_60_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_60_out),
    .w_V_60_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_60_out_ap_vld),
    .w_V_59_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_59_out),
    .w_V_59_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_59_out_ap_vld),
    .w_V_58_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_58_out),
    .w_V_58_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_58_out_ap_vld),
    .w_V_57_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_57_out),
    .w_V_57_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_57_out_ap_vld),
    .w_V_56_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_56_out),
    .w_V_56_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_56_out_ap_vld),
    .w_V_55_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_55_out),
    .w_V_55_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_55_out_ap_vld),
    .w_V_54_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_54_out),
    .w_V_54_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_54_out_ap_vld),
    .w_V_53_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_53_out),
    .w_V_53_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_53_out_ap_vld),
    .w_V_52_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_52_out),
    .w_V_52_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_52_out_ap_vld),
    .w_V_51_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_51_out),
    .w_V_51_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_51_out_ap_vld),
    .w_V_50_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_50_out),
    .w_V_50_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_50_out_ap_vld),
    .w_V_49_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_49_out),
    .w_V_49_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_49_out_ap_vld),
    .w_V_48_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_48_out),
    .w_V_48_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_48_out_ap_vld),
    .w_V_47_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_47_out),
    .w_V_47_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_47_out_ap_vld),
    .w_V_46_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_46_out),
    .w_V_46_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_46_out_ap_vld),
    .w_V_45_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_45_out),
    .w_V_45_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_45_out_ap_vld),
    .w_V_44_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_44_out),
    .w_V_44_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_44_out_ap_vld),
    .w_V_43_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_43_out),
    .w_V_43_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_43_out_ap_vld),
    .w_V_42_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_42_out),
    .w_V_42_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_42_out_ap_vld),
    .w_V_41_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_41_out),
    .w_V_41_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_41_out_ap_vld),
    .w_V_40_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_40_out),
    .w_V_40_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_40_out_ap_vld),
    .w_V_39_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_39_out),
    .w_V_39_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_39_out_ap_vld),
    .w_V_38_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_38_out),
    .w_V_38_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_38_out_ap_vld),
    .w_V_37_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_37_out),
    .w_V_37_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_37_out_ap_vld),
    .w_V_36_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_36_out),
    .w_V_36_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_36_out_ap_vld),
    .w_V_35_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_35_out),
    .w_V_35_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_35_out_ap_vld),
    .w_V_34_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_34_out),
    .w_V_34_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_34_out_ap_vld),
    .w_V_33_out(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_33_out),
    .w_V_33_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_33_out_ap_vld)
);

sha256_acc_sha256_acc_Pipeline_VITIS_LOOP_30_3 grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_ap_start),
    .ap_done(grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_ap_done),
    .ap_idle(grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_ap_idle),
    .ap_ready(grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_ap_ready),
    .w_V_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_out),
    .w_V_1_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_1_out),
    .w_V_2_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_2_out),
    .w_V_3_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_3_out),
    .w_V_4_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_4_out),
    .w_V_5_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_5_out),
    .w_V_6_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_6_out),
    .w_V_7_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_7_out),
    .w_V_8_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_8_out),
    .w_V_9_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_9_out),
    .w_V_10_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_10_out),
    .w_V_11_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_11_out),
    .w_V_12_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_12_out),
    .w_V_13_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_13_out),
    .w_V_14_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_14_out),
    .w_V_15_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_w_V_15_out),
    .w_V_33_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_33_out),
    .w_V_34_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_34_out),
    .w_V_35_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_35_out),
    .w_V_36_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_36_out),
    .w_V_37_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_37_out),
    .w_V_38_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_38_out),
    .w_V_39_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_39_out),
    .w_V_40_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_40_out),
    .w_V_41_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_41_out),
    .w_V_42_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_42_out),
    .w_V_43_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_43_out),
    .w_V_44_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_44_out),
    .w_V_45_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_45_out),
    .w_V_46_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_46_out),
    .w_V_47_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_47_out),
    .w_V_48_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_48_out),
    .w_V_49_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_49_out),
    .w_V_50_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_50_out),
    .w_V_51_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_51_out),
    .w_V_52_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_52_out),
    .w_V_53_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_53_out),
    .w_V_54_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_54_out),
    .w_V_55_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_55_out),
    .w_V_56_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_56_out),
    .w_V_57_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_57_out),
    .w_V_58_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_58_out),
    .w_V_59_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_59_out),
    .w_V_60_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_60_out),
    .w_V_61_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_61_out),
    .w_V_62_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_62_out),
    .w_V_63_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_63_out),
    .w_V_64_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_64_out),
    .w_V_65_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_65_out),
    .w_V_66_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_66_out),
    .w_V_67_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_67_out),
    .w_V_68_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_68_out),
    .w_V_69_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_69_out),
    .w_V_70_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_70_out),
    .w_V_71_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_71_out),
    .w_V_72_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_72_out),
    .w_V_73_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_73_out),
    .w_V_74_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_74_out),
    .w_V_75_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_75_out),
    .w_V_76_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_76_out),
    .w_V_77_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_77_out),
    .w_V_78_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_78_out),
    .w_V_79_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_79_out),
    .w_V_80_reload(grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_w_V_80_out),
    .h_val_V_out(grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_h_val_V_out),
    .h_val_V_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_h_val_V_out_ap_vld),
    .g_V_out(grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_g_V_out),
    .g_V_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_g_V_out_ap_vld),
    .f_V_out(grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_f_V_out),
    .f_V_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_f_V_out_ap_vld),
    .e_V_2_out(grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_e_V_2_out),
    .e_V_2_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_e_V_2_out_ap_vld),
    .d_V_out(grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_d_V_out),
    .d_V_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_d_V_out_ap_vld),
    .c_V_out(grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_c_V_out),
    .c_V_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_c_V_out_ap_vld),
    .b_V_out(grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_b_V_out),
    .b_V_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_b_V_out_ap_vld),
    .a_V_2_out(grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_a_V_2_out),
    .a_V_2_out_ap_vld(grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_a_V_2_out_ap_vld)
);

sha256_acc_sha256_acc_Pipeline_VITIS_LOOP_40_4 grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_ap_start),
    .ap_done(grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_ap_done),
    .ap_idle(grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_ap_idle),
    .ap_ready(grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_ap_ready),
    .out_stream_TREADY(grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_out_stream_TREADY),
    .res_V_address0(grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_res_V_address0),
    .res_V_ce0(grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_res_V_ce0),
    .res_V_q0(res_V_q0),
    .out_stream_TDATA(grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_out_stream_TDATA),
    .out_stream_TVALID(grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_out_stream_TVALID),
    .out_stream_TKEEP(grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_out_stream_TKEEP),
    .out_stream_TSTRB(grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_out_stream_TSTRB),
    .out_stream_TLAST(grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_out_stream_TLAST)
);

sha256_acc_CONTROL_BUS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_BUS_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_BUS_DATA_WIDTH ))
CONTROL_BUS_s_axi_U(
    .AWVALID(s_axi_CONTROL_BUS_AWVALID),
    .AWREADY(s_axi_CONTROL_BUS_AWREADY),
    .AWADDR(s_axi_CONTROL_BUS_AWADDR),
    .WVALID(s_axi_CONTROL_BUS_WVALID),
    .WREADY(s_axi_CONTROL_BUS_WREADY),
    .WDATA(s_axi_CONTROL_BUS_WDATA),
    .WSTRB(s_axi_CONTROL_BUS_WSTRB),
    .ARVALID(s_axi_CONTROL_BUS_ARVALID),
    .ARREADY(s_axi_CONTROL_BUS_ARREADY),
    .ARADDR(s_axi_CONTROL_BUS_ARADDR),
    .RVALID(s_axi_CONTROL_BUS_RVALID),
    .RREADY(s_axi_CONTROL_BUS_RREADY),
    .RDATA(s_axi_CONTROL_BUS_RDATA),
    .RRESP(s_axi_CONTROL_BUS_RRESP),
    .BVALID(s_axi_CONTROL_BUS_BVALID),
    .BREADY(s_axi_CONTROL_BUS_BREADY),
    .BRESP(s_axi_CONTROL_BUS_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

sha256_acc_regslice_both #(
    .DataWidth( 32 ))
regslice_both_in_stream_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TDATA),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_U_ack_in),
    .data_out(in_stream_TDATA_int_regslice),
    .vld_out(in_stream_TVALID_int_regslice),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_U_apdone_blk)
);

sha256_acc_regslice_both #(
    .DataWidth( 32 ))
regslice_both_out_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_out_stream_TDATA),
    .vld_in(grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_out_stream_TVALID),
    .ack_in(out_stream_TREADY_int_regslice),
    .data_out(out_stream_TDATA),
    .vld_out(regslice_both_out_stream_V_data_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_data_V_U_apdone_blk)
);

sha256_acc_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_out_stream_TKEEP),
    .vld_in(grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_out_stream_TVALID),
    .ack_in(regslice_both_out_stream_V_keep_V_U_ack_in_dummy),
    .data_out(out_stream_TKEEP),
    .vld_out(regslice_both_out_stream_V_keep_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_keep_V_U_apdone_blk)
);

sha256_acc_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_out_stream_TSTRB),
    .vld_in(grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_out_stream_TVALID),
    .ack_in(regslice_both_out_stream_V_strb_V_U_ack_in_dummy),
    .data_out(out_stream_TSTRB),
    .vld_out(regslice_both_out_stream_V_strb_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_strb_V_U_apdone_blk)
);

sha256_acc_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_out_stream_TLAST),
    .vld_in(grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_out_stream_TVALID),
    .ack_in(regslice_both_out_stream_V_last_V_U_ack_in_dummy),
    .data_out(out_stream_TLAST),
    .vld_out(regslice_both_out_stream_V_last_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_ap_start_reg <= 1'b1;
        end else if ((grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_ap_ready == 1'b1)) begin
            grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_ap_start_reg <= 1'b1;
        end else if ((grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_ap_ready == 1'b1)) begin
            grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_ap_start_reg <= 1'b1;
        end else if ((grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_ap_ready == 1'b1)) begin
            grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state12)) begin
            grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_ap_start_reg <= 1'b1;
        end else if ((grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_ap_ready == 1'b1)) begin
            grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_ap_start_reg <= 1'b0;
        end
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_ap_done == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state14))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state14))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_stream_TREADY_int_regslice = grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_in_stream_TREADY;
    end else begin
        in_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        res_V_address0 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        res_V_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        res_V_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        res_V_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        res_V_address0 = grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_res_V_address0;
    end else begin
        res_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        res_V_address1 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        res_V_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        res_V_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        res_V_address1 = 64'd0;
    end else begin
        res_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8))) begin
        res_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        res_V_ce0 = grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_res_V_ce0;
    end else begin
        res_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8))) begin
        res_V_ce1 = 1'b1;
    end else begin
        res_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        res_V_d0 = add_ln186_9_fu_959_p2;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        res_V_d0 = add_ln186_fu_939_p2;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        res_V_d0 = add_ln186_6_fu_919_p2;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        res_V_d0 = add_ln186_4_fu_899_p2;
    end else begin
        res_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        res_V_d1 = add_ln186_8_fu_952_p2;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        res_V_d1 = add_ln186_7_fu_932_p2;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        res_V_d1 = add_ln186_5_fu_912_p2;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        res_V_d1 = add_ln186_3_fu_892_p2;
    end else begin
        res_V_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8))) begin
        res_V_we0 = 1'b1;
    end else begin
        res_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8))) begin
        res_V_we1 = 1'b1;
    end else begin
        res_V_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln186_3_fu_892_p2 = (grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_a_V_2_out + 32'd1779033703);

assign add_ln186_4_fu_899_p2 = ($signed(grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_b_V_out) + $signed(32'd3144134277));

assign add_ln186_5_fu_912_p2 = (grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_c_V_out + 32'd1013904242);

assign add_ln186_6_fu_919_p2 = ($signed(grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_d_V_out) + $signed(32'd2773480762));

assign add_ln186_7_fu_932_p2 = (grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_e_V_2_out + 32'd1359893119);

assign add_ln186_8_fu_952_p2 = (grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_g_V_out + 32'd528734635);

assign add_ln186_9_fu_959_p2 = (grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_h_val_V_out + 32'd1541459225);

assign add_ln186_fu_939_p2 = ($signed(grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_f_V_out) + $signed(32'd2600822924));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_ap_start = grp_sha256_acc_Pipeline_VITIS_LOOP_15_1_fu_449_ap_start_reg;

assign grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_ap_start = grp_sha256_acc_Pipeline_VITIS_LOOP_21_2_fu_471_ap_start_reg;

assign grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_ap_start = grp_sha256_acc_Pipeline_VITIS_LOOP_30_3_fu_539_ap_start_reg;

assign grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_ap_start = grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_ap_start_reg;

assign grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_out_stream_TREADY = (out_stream_TREADY_int_regslice & ap_CS_fsm_state13);

assign in_stream_TREADY = regslice_both_in_stream_U_ack_in;

assign out_stream_TVALID = regslice_both_out_stream_V_data_V_U_vld_out;

assign out_stream_TVALID_int_regslice = grp_sha256_acc_Pipeline_VITIS_LOOP_40_4_fu_617_out_stream_TVALID;


reg find_kernel_block = 0;
// synthesis translate_off
`include "sha256_acc_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //sha256_acc

