// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sha256_acc_sha256_acc_Pipeline_VITIS_LOOP_15_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_stream_TVALID,
        in_stream_TDATA,
        in_stream_TREADY,
        w_V_15_out,
        w_V_15_out_ap_vld,
        w_V_14_out,
        w_V_14_out_ap_vld,
        w_V_13_out,
        w_V_13_out_ap_vld,
        w_V_12_out,
        w_V_12_out_ap_vld,
        w_V_11_out,
        w_V_11_out_ap_vld,
        w_V_10_out,
        w_V_10_out_ap_vld,
        w_V_9_out,
        w_V_9_out_ap_vld,
        w_V_8_out,
        w_V_8_out_ap_vld,
        w_V_7_out,
        w_V_7_out_ap_vld,
        w_V_6_out,
        w_V_6_out_ap_vld,
        w_V_5_out,
        w_V_5_out_ap_vld,
        w_V_4_out,
        w_V_4_out_ap_vld,
        w_V_3_out,
        w_V_3_out_ap_vld,
        w_V_2_out,
        w_V_2_out_ap_vld,
        w_V_1_out,
        w_V_1_out_ap_vld,
        w_V_out,
        w_V_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in_stream_TVALID;
input  [31:0] in_stream_TDATA;
output   in_stream_TREADY;
output  [31:0] w_V_15_out;
output   w_V_15_out_ap_vld;
output  [31:0] w_V_14_out;
output   w_V_14_out_ap_vld;
output  [31:0] w_V_13_out;
output   w_V_13_out_ap_vld;
output  [31:0] w_V_12_out;
output   w_V_12_out_ap_vld;
output  [31:0] w_V_11_out;
output   w_V_11_out_ap_vld;
output  [31:0] w_V_10_out;
output   w_V_10_out_ap_vld;
output  [31:0] w_V_9_out;
output   w_V_9_out_ap_vld;
output  [31:0] w_V_8_out;
output   w_V_8_out_ap_vld;
output  [31:0] w_V_7_out;
output   w_V_7_out_ap_vld;
output  [31:0] w_V_6_out;
output   w_V_6_out_ap_vld;
output  [31:0] w_V_5_out;
output   w_V_5_out_ap_vld;
output  [31:0] w_V_4_out;
output   w_V_4_out_ap_vld;
output  [31:0] w_V_3_out;
output   w_V_3_out_ap_vld;
output  [31:0] w_V_2_out;
output   w_V_2_out_ap_vld;
output  [31:0] w_V_1_out;
output   w_V_1_out_ap_vld;
output  [31:0] w_V_out;
output   w_V_out_ap_vld;

reg ap_idle;
reg in_stream_TREADY;
reg w_V_15_out_ap_vld;
reg w_V_14_out_ap_vld;
reg w_V_13_out_ap_vld;
reg w_V_12_out_ap_vld;
reg w_V_11_out_ap_vld;
reg w_V_10_out_ap_vld;
reg w_V_9_out_ap_vld;
reg w_V_8_out_ap_vld;
reg w_V_7_out_ap_vld;
reg w_V_6_out_ap_vld;
reg w_V_5_out_ap_vld;
reg w_V_4_out_ap_vld;
reg w_V_3_out_ap_vld;
reg w_V_2_out_ap_vld;
reg w_V_1_out_ap_vld;
reg w_V_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln15_fu_292_p2;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in_stream_TDATA_blk_n;
reg   [4:0] i_fu_98;
wire   [4:0] add_ln15_fu_298_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_i_2;
reg   [31:0] w_V_fu_102;
wire   [3:0] trunc_ln17_fu_304_p1;
reg   [31:0] w_V_1_fu_106;
reg   [31:0] w_V_2_fu_110;
reg   [31:0] w_V_3_fu_114;
reg   [31:0] w_V_4_fu_118;
reg   [31:0] w_V_5_fu_122;
reg   [31:0] w_V_6_fu_126;
reg   [31:0] w_V_7_fu_130;
reg   [31:0] w_V_8_fu_134;
reg   [31:0] w_V_9_fu_138;
reg   [31:0] w_V_10_fu_142;
reg   [31:0] w_V_11_fu_146;
reg   [31:0] w_V_12_fu_150;
reg   [31:0] w_V_13_fu_154;
reg   [31:0] w_V_14_fu_158;
reg   [31:0] w_V_15_fu_162;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
reg    ap_condition_249;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

sha256_acc_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_292_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_249)) begin
        if ((icmp_ln15_fu_292_p2 == 1'd0)) begin
            i_fu_98 <= add_ln15_fu_298_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_98 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_292_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (trunc_ln17_fu_304_p1 == 4'd10) & (icmp_ln15_fu_292_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_V_10_fu_142 <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_292_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (trunc_ln17_fu_304_p1 == 4'd11) & (icmp_ln15_fu_292_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_V_11_fu_146 <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_292_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (trunc_ln17_fu_304_p1 == 4'd12) & (icmp_ln15_fu_292_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_V_12_fu_150 <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_292_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (trunc_ln17_fu_304_p1 == 4'd13) & (icmp_ln15_fu_292_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_V_13_fu_154 <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_292_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (trunc_ln17_fu_304_p1 == 4'd14) & (icmp_ln15_fu_292_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_V_14_fu_158 <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_292_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (trunc_ln17_fu_304_p1 == 4'd15) & (icmp_ln15_fu_292_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_V_15_fu_162 <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_292_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (trunc_ln17_fu_304_p1 == 4'd1) & (icmp_ln15_fu_292_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_V_1_fu_106 <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_292_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (trunc_ln17_fu_304_p1 == 4'd2) & (icmp_ln15_fu_292_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_V_2_fu_110 <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_292_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (trunc_ln17_fu_304_p1 == 4'd3) & (icmp_ln15_fu_292_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_V_3_fu_114 <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_292_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (trunc_ln17_fu_304_p1 == 4'd4) & (icmp_ln15_fu_292_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_V_4_fu_118 <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_292_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (trunc_ln17_fu_304_p1 == 4'd5) & (icmp_ln15_fu_292_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_V_5_fu_122 <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_292_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (trunc_ln17_fu_304_p1 == 4'd6) & (icmp_ln15_fu_292_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_V_6_fu_126 <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_292_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (trunc_ln17_fu_304_p1 == 4'd7) & (icmp_ln15_fu_292_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_V_7_fu_130 <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_292_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (trunc_ln17_fu_304_p1 == 4'd8) & (icmp_ln15_fu_292_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_V_8_fu_134 <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_292_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (trunc_ln17_fu_304_p1 == 4'd9) & (icmp_ln15_fu_292_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_V_9_fu_138 <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_292_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (trunc_ln17_fu_304_p1 == 4'd0) & (icmp_ln15_fu_292_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        w_V_fu_102 <= in_stream_TDATA;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) | ((icmp_ln15_fu_292_p2 == 1'd0) & (in_stream_TVALID == 1'b0)))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_292_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (icmp_ln15_fu_292_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_292_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_292_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_i_2 = 5'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_98;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln15_fu_292_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        in_stream_TDATA_blk_n = in_stream_TVALID;
    end else begin
        in_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_292_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (icmp_ln15_fu_292_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        in_stream_TREADY = 1'b1;
    end else begin
        in_stream_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_292_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (icmp_ln15_fu_292_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        w_V_10_out_ap_vld = 1'b1;
    end else begin
        w_V_10_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_292_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (icmp_ln15_fu_292_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        w_V_11_out_ap_vld = 1'b1;
    end else begin
        w_V_11_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_292_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (icmp_ln15_fu_292_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        w_V_12_out_ap_vld = 1'b1;
    end else begin
        w_V_12_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_292_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (icmp_ln15_fu_292_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        w_V_13_out_ap_vld = 1'b1;
    end else begin
        w_V_13_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_292_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (icmp_ln15_fu_292_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        w_V_14_out_ap_vld = 1'b1;
    end else begin
        w_V_14_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_292_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (icmp_ln15_fu_292_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        w_V_15_out_ap_vld = 1'b1;
    end else begin
        w_V_15_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_292_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (icmp_ln15_fu_292_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        w_V_1_out_ap_vld = 1'b1;
    end else begin
        w_V_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_292_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (icmp_ln15_fu_292_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        w_V_2_out_ap_vld = 1'b1;
    end else begin
        w_V_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_292_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (icmp_ln15_fu_292_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        w_V_3_out_ap_vld = 1'b1;
    end else begin
        w_V_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_292_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (icmp_ln15_fu_292_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        w_V_4_out_ap_vld = 1'b1;
    end else begin
        w_V_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_292_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (icmp_ln15_fu_292_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        w_V_5_out_ap_vld = 1'b1;
    end else begin
        w_V_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_292_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (icmp_ln15_fu_292_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        w_V_6_out_ap_vld = 1'b1;
    end else begin
        w_V_6_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_292_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (icmp_ln15_fu_292_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        w_V_7_out_ap_vld = 1'b1;
    end else begin
        w_V_7_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_292_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (icmp_ln15_fu_292_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        w_V_8_out_ap_vld = 1'b1;
    end else begin
        w_V_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_292_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (icmp_ln15_fu_292_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        w_V_9_out_ap_vld = 1'b1;
    end else begin
        w_V_9_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln15_fu_292_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (icmp_ln15_fu_292_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        w_V_out_ap_vld = 1'b1;
    end else begin
        w_V_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln15_fu_298_p2 = (ap_sig_allocacmp_i_2 + 5'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((icmp_ln15_fu_292_p2 == 1'd0) & (in_stream_TVALID == 1'b0)));
end

always @ (*) begin
    ap_condition_249 = (~((ap_start_int == 1'b0) | ((icmp_ln15_fu_292_p2 == 1'd0) & (in_stream_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln15_fu_292_p2 = ((ap_sig_allocacmp_i_2 == 5'd16) ? 1'b1 : 1'b0);

assign trunc_ln17_fu_304_p1 = ap_sig_allocacmp_i_2[3:0];

assign w_V_10_out = w_V_10_fu_142;

assign w_V_11_out = w_V_11_fu_146;

assign w_V_12_out = w_V_12_fu_150;

assign w_V_13_out = w_V_13_fu_154;

assign w_V_14_out = w_V_14_fu_158;

assign w_V_15_out = w_V_15_fu_162;

assign w_V_1_out = w_V_1_fu_106;

assign w_V_2_out = w_V_2_fu_110;

assign w_V_3_out = w_V_3_fu_114;

assign w_V_4_out = w_V_4_fu_118;

assign w_V_5_out = w_V_5_fu_122;

assign w_V_6_out = w_V_6_fu_126;

assign w_V_7_out = w_V_7_fu_130;

assign w_V_8_out = w_V_8_fu_134;

assign w_V_9_out = w_V_9_fu_138;

assign w_V_out = w_V_fu_102;

endmodule //sha256_acc_sha256_acc_Pipeline_VITIS_LOOP_15_1
