-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sha256_acc_sha256_acc_Pipeline_VITIS_LOOP_30_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    w_V_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_1_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_2_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_4_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_5_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_6_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_7_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_8_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_9_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_10_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_11_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_12_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_13_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_14_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_15_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_33_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_34_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_35_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_36_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_37_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_38_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_39_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_40_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_41_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_42_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_43_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_44_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_45_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_46_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_47_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_48_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_49_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_50_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_51_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_52_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_53_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_54_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_55_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_56_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_57_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_58_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_59_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_60_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_61_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_62_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_63_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_64_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_65_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_66_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_67_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_68_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_69_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_70_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_71_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_72_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_73_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_74_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_75_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_76_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_77_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_78_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_79_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    w_V_80_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    h_val_V_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    h_val_V_out_ap_vld : OUT STD_LOGIC;
    g_V_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    g_V_out_ap_vld : OUT STD_LOGIC;
    f_V_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    f_V_out_ap_vld : OUT STD_LOGIC;
    e_V_2_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    e_V_2_out_ap_vld : OUT STD_LOGIC;
    d_V_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    d_V_out_ap_vld : OUT STD_LOGIC;
    c_V_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    c_V_out_ap_vld : OUT STD_LOGIC;
    b_V_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    b_V_out_ap_vld : OUT STD_LOGIC;
    a_V_2_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    a_V_2_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of sha256_acc_sha256_acc_Pipeline_VITIS_LOOP_30_3 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_BB67AE85 : STD_LOGIC_VECTOR (31 downto 0) := "10111011011001111010111010000101";
    constant ap_const_lv32_A54FF53A : STD_LOGIC_VECTOR (31 downto 0) := "10100101010011111111010100111010";
    constant ap_const_lv32_9B05688C : STD_LOGIC_VECTOR (31 downto 0) := "10011011000001010110100010001100";
    constant ap_const_lv32_6A09E667 : STD_LOGIC_VECTOR (31 downto 0) := "01101010000010011110011001100111";
    constant ap_const_lv32_5BE0CD19 : STD_LOGIC_VECTOR (31 downto 0) := "01011011111000001100110100011001";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv32_3C6EF372 : STD_LOGIC_VECTOR (31 downto 0) := "00111100011011101111001101110010";
    constant ap_const_lv32_510E527F : STD_LOGIC_VECTOR (31 downto 0) := "01010001000011100101001001111111";
    constant ap_const_lv32_1F83D9AB : STD_LOGIC_VECTOR (31 downto 0) := "00011111100000111101100110101011";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal icmp_ln30_reg_1312 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal k_V_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal k_V_ce0 : STD_LOGIC;
    signal k_V_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln30_fu_769_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal tmp_4_fu_790_p66 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_4_reg_1321 : STD_LOGIC_VECTOR (31 downto 0);
    signal a_V_2_reg_1326 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal c_V_reg_1338 : STD_LOGIC_VECTOR (31 downto 0);
    signal t1_V_fu_1070_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal t1_V_reg_1345 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal zext_ln30_fu_781_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal c_V_1_fu_232 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal d_V_fu_236 : STD_LOGIC_VECTOR (31 downto 0);
    signal g_V_1_fu_240 : STD_LOGIC_VECTOR (31 downto 0);
    signal b_V_fu_244 : STD_LOGIC_VECTOR (31 downto 0);
    signal a_V_fu_1200_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal h_val_V_fu_248 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_fu_252 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln30_fu_775_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_sig_allocacmp_i_1 : STD_LOGIC_VECTOR (6 downto 0);
    signal d_V_1_fu_256 : STD_LOGIC_VECTOR (31 downto 0);
    signal f_V_fu_260 : STD_LOGIC_VECTOR (31 downto 0);
    signal e_V_fu_1190_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal h_val_V_1_fu_264 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage1_01001 : BOOLEAN;
    signal tmp_4_fu_790_p65 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln1669_fu_961_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal r_V_5_fu_951_p4 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln1669_1_fu_983_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_6_fu_973_p4 : STD_LOGIC_VECTOR (20 downto 0);
    signal trunc_ln1669_2_fu_1005_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal r_V_7_fu_995_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal ret_V_12_fu_965_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ret_V_13_fu_987_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln1499_fu_1017_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ret_V_14_fu_1009_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_fu_1035_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ret_V_15_fu_1029_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ret_V_16_fu_1041_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ret_V_4_fu_1047_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln186_1_fu_1059_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ret_V_fu_1023_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln186_2_fu_1064_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln186_fu_1053_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln1669_3_fu_1106_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal r_V_8_fu_1097_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal trunc_ln1669_4_fu_1126_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal r_V_9_fu_1117_p4 : STD_LOGIC_VECTOR (18 downto 0);
    signal trunc_ln1669_5_fu_1146_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal r_V_s_fu_1137_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal ret_V_17_fu_1109_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ret_V_18_fu_1129_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln1499_3_fu_1157_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ret_V_19_fu_1149_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal xor_ln1499_5_fu_1169_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ret_V_20_fu_1174_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ret_V_21_fu_1179_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ret_V_11_fu_1184_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln186_5_fu_1195_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ret_V_8_fu_1163_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_idle_pp0_1to1 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component sha256_acc_mux_646_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        din8_WIDTH : INTEGER;
        din9_WIDTH : INTEGER;
        din10_WIDTH : INTEGER;
        din11_WIDTH : INTEGER;
        din12_WIDTH : INTEGER;
        din13_WIDTH : INTEGER;
        din14_WIDTH : INTEGER;
        din15_WIDTH : INTEGER;
        din16_WIDTH : INTEGER;
        din17_WIDTH : INTEGER;
        din18_WIDTH : INTEGER;
        din19_WIDTH : INTEGER;
        din20_WIDTH : INTEGER;
        din21_WIDTH : INTEGER;
        din22_WIDTH : INTEGER;
        din23_WIDTH : INTEGER;
        din24_WIDTH : INTEGER;
        din25_WIDTH : INTEGER;
        din26_WIDTH : INTEGER;
        din27_WIDTH : INTEGER;
        din28_WIDTH : INTEGER;
        din29_WIDTH : INTEGER;
        din30_WIDTH : INTEGER;
        din31_WIDTH : INTEGER;
        din32_WIDTH : INTEGER;
        din33_WIDTH : INTEGER;
        din34_WIDTH : INTEGER;
        din35_WIDTH : INTEGER;
        din36_WIDTH : INTEGER;
        din37_WIDTH : INTEGER;
        din38_WIDTH : INTEGER;
        din39_WIDTH : INTEGER;
        din40_WIDTH : INTEGER;
        din41_WIDTH : INTEGER;
        din42_WIDTH : INTEGER;
        din43_WIDTH : INTEGER;
        din44_WIDTH : INTEGER;
        din45_WIDTH : INTEGER;
        din46_WIDTH : INTEGER;
        din47_WIDTH : INTEGER;
        din48_WIDTH : INTEGER;
        din49_WIDTH : INTEGER;
        din50_WIDTH : INTEGER;
        din51_WIDTH : INTEGER;
        din52_WIDTH : INTEGER;
        din53_WIDTH : INTEGER;
        din54_WIDTH : INTEGER;
        din55_WIDTH : INTEGER;
        din56_WIDTH : INTEGER;
        din57_WIDTH : INTEGER;
        din58_WIDTH : INTEGER;
        din59_WIDTH : INTEGER;
        din60_WIDTH : INTEGER;
        din61_WIDTH : INTEGER;
        din62_WIDTH : INTEGER;
        din63_WIDTH : INTEGER;
        din64_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        din5 : IN STD_LOGIC_VECTOR (31 downto 0);
        din6 : IN STD_LOGIC_VECTOR (31 downto 0);
        din7 : IN STD_LOGIC_VECTOR (31 downto 0);
        din8 : IN STD_LOGIC_VECTOR (31 downto 0);
        din9 : IN STD_LOGIC_VECTOR (31 downto 0);
        din10 : IN STD_LOGIC_VECTOR (31 downto 0);
        din11 : IN STD_LOGIC_VECTOR (31 downto 0);
        din12 : IN STD_LOGIC_VECTOR (31 downto 0);
        din13 : IN STD_LOGIC_VECTOR (31 downto 0);
        din14 : IN STD_LOGIC_VECTOR (31 downto 0);
        din15 : IN STD_LOGIC_VECTOR (31 downto 0);
        din16 : IN STD_LOGIC_VECTOR (31 downto 0);
        din17 : IN STD_LOGIC_VECTOR (31 downto 0);
        din18 : IN STD_LOGIC_VECTOR (31 downto 0);
        din19 : IN STD_LOGIC_VECTOR (31 downto 0);
        din20 : IN STD_LOGIC_VECTOR (31 downto 0);
        din21 : IN STD_LOGIC_VECTOR (31 downto 0);
        din22 : IN STD_LOGIC_VECTOR (31 downto 0);
        din23 : IN STD_LOGIC_VECTOR (31 downto 0);
        din24 : IN STD_LOGIC_VECTOR (31 downto 0);
        din25 : IN STD_LOGIC_VECTOR (31 downto 0);
        din26 : IN STD_LOGIC_VECTOR (31 downto 0);
        din27 : IN STD_LOGIC_VECTOR (31 downto 0);
        din28 : IN STD_LOGIC_VECTOR (31 downto 0);
        din29 : IN STD_LOGIC_VECTOR (31 downto 0);
        din30 : IN STD_LOGIC_VECTOR (31 downto 0);
        din31 : IN STD_LOGIC_VECTOR (31 downto 0);
        din32 : IN STD_LOGIC_VECTOR (31 downto 0);
        din33 : IN STD_LOGIC_VECTOR (31 downto 0);
        din34 : IN STD_LOGIC_VECTOR (31 downto 0);
        din35 : IN STD_LOGIC_VECTOR (31 downto 0);
        din36 : IN STD_LOGIC_VECTOR (31 downto 0);
        din37 : IN STD_LOGIC_VECTOR (31 downto 0);
        din38 : IN STD_LOGIC_VECTOR (31 downto 0);
        din39 : IN STD_LOGIC_VECTOR (31 downto 0);
        din40 : IN STD_LOGIC_VECTOR (31 downto 0);
        din41 : IN STD_LOGIC_VECTOR (31 downto 0);
        din42 : IN STD_LOGIC_VECTOR (31 downto 0);
        din43 : IN STD_LOGIC_VECTOR (31 downto 0);
        din44 : IN STD_LOGIC_VECTOR (31 downto 0);
        din45 : IN STD_LOGIC_VECTOR (31 downto 0);
        din46 : IN STD_LOGIC_VECTOR (31 downto 0);
        din47 : IN STD_LOGIC_VECTOR (31 downto 0);
        din48 : IN STD_LOGIC_VECTOR (31 downto 0);
        din49 : IN STD_LOGIC_VECTOR (31 downto 0);
        din50 : IN STD_LOGIC_VECTOR (31 downto 0);
        din51 : IN STD_LOGIC_VECTOR (31 downto 0);
        din52 : IN STD_LOGIC_VECTOR (31 downto 0);
        din53 : IN STD_LOGIC_VECTOR (31 downto 0);
        din54 : IN STD_LOGIC_VECTOR (31 downto 0);
        din55 : IN STD_LOGIC_VECTOR (31 downto 0);
        din56 : IN STD_LOGIC_VECTOR (31 downto 0);
        din57 : IN STD_LOGIC_VECTOR (31 downto 0);
        din58 : IN STD_LOGIC_VECTOR (31 downto 0);
        din59 : IN STD_LOGIC_VECTOR (31 downto 0);
        din60 : IN STD_LOGIC_VECTOR (31 downto 0);
        din61 : IN STD_LOGIC_VECTOR (31 downto 0);
        din62 : IN STD_LOGIC_VECTOR (31 downto 0);
        din63 : IN STD_LOGIC_VECTOR (31 downto 0);
        din64 : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component sha256_acc_sha256_acc_Pipeline_VITIS_LOOP_30_3_k_V_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component sha256_acc_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    k_V_U : component sha256_acc_sha256_acc_Pipeline_VITIS_LOOP_30_3_k_V_ROM_AUTO_1R
    generic map (
        DataWidth => 32,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => k_V_address0,
        ce0 => k_V_ce0,
        q0 => k_V_q0);

    mux_646_32_1_1_U87 : component sha256_acc_mux_646_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 32,
        din5_WIDTH => 32,
        din6_WIDTH => 32,
        din7_WIDTH => 32,
        din8_WIDTH => 32,
        din9_WIDTH => 32,
        din10_WIDTH => 32,
        din11_WIDTH => 32,
        din12_WIDTH => 32,
        din13_WIDTH => 32,
        din14_WIDTH => 32,
        din15_WIDTH => 32,
        din16_WIDTH => 32,
        din17_WIDTH => 32,
        din18_WIDTH => 32,
        din19_WIDTH => 32,
        din20_WIDTH => 32,
        din21_WIDTH => 32,
        din22_WIDTH => 32,
        din23_WIDTH => 32,
        din24_WIDTH => 32,
        din25_WIDTH => 32,
        din26_WIDTH => 32,
        din27_WIDTH => 32,
        din28_WIDTH => 32,
        din29_WIDTH => 32,
        din30_WIDTH => 32,
        din31_WIDTH => 32,
        din32_WIDTH => 32,
        din33_WIDTH => 32,
        din34_WIDTH => 32,
        din35_WIDTH => 32,
        din36_WIDTH => 32,
        din37_WIDTH => 32,
        din38_WIDTH => 32,
        din39_WIDTH => 32,
        din40_WIDTH => 32,
        din41_WIDTH => 32,
        din42_WIDTH => 32,
        din43_WIDTH => 32,
        din44_WIDTH => 32,
        din45_WIDTH => 32,
        din46_WIDTH => 32,
        din47_WIDTH => 32,
        din48_WIDTH => 32,
        din49_WIDTH => 32,
        din50_WIDTH => 32,
        din51_WIDTH => 32,
        din52_WIDTH => 32,
        din53_WIDTH => 32,
        din54_WIDTH => 32,
        din55_WIDTH => 32,
        din56_WIDTH => 32,
        din57_WIDTH => 32,
        din58_WIDTH => 32,
        din59_WIDTH => 32,
        din60_WIDTH => 32,
        din61_WIDTH => 32,
        din62_WIDTH => 32,
        din63_WIDTH => 32,
        din64_WIDTH => 6,
        dout_WIDTH => 32)
    port map (
        din0 => w_V_reload,
        din1 => w_V_1_reload,
        din2 => w_V_2_reload,
        din3 => w_V_3_reload,
        din4 => w_V_4_reload,
        din5 => w_V_5_reload,
        din6 => w_V_6_reload,
        din7 => w_V_7_reload,
        din8 => w_V_8_reload,
        din9 => w_V_9_reload,
        din10 => w_V_10_reload,
        din11 => w_V_11_reload,
        din12 => w_V_12_reload,
        din13 => w_V_13_reload,
        din14 => w_V_14_reload,
        din15 => w_V_15_reload,
        din16 => w_V_33_reload,
        din17 => w_V_34_reload,
        din18 => w_V_35_reload,
        din19 => w_V_36_reload,
        din20 => w_V_37_reload,
        din21 => w_V_38_reload,
        din22 => w_V_39_reload,
        din23 => w_V_40_reload,
        din24 => w_V_41_reload,
        din25 => w_V_42_reload,
        din26 => w_V_43_reload,
        din27 => w_V_44_reload,
        din28 => w_V_45_reload,
        din29 => w_V_46_reload,
        din30 => w_V_47_reload,
        din31 => w_V_48_reload,
        din32 => w_V_49_reload,
        din33 => w_V_50_reload,
        din34 => w_V_51_reload,
        din35 => w_V_52_reload,
        din36 => w_V_53_reload,
        din37 => w_V_54_reload,
        din38 => w_V_55_reload,
        din39 => w_V_56_reload,
        din40 => w_V_57_reload,
        din41 => w_V_58_reload,
        din42 => w_V_59_reload,
        din43 => w_V_60_reload,
        din44 => w_V_61_reload,
        din45 => w_V_62_reload,
        din46 => w_V_63_reload,
        din47 => w_V_64_reload,
        din48 => w_V_65_reload,
        din49 => w_V_66_reload,
        din50 => w_V_67_reload,
        din51 => w_V_68_reload,
        din52 => w_V_69_reload,
        din53 => w_V_70_reload,
        din54 => w_V_71_reload,
        din55 => w_V_72_reload,
        din56 => w_V_73_reload,
        din57 => w_V_74_reload,
        din58 => w_V_75_reload,
        din59 => w_V_76_reload,
        din60 => w_V_77_reload,
        din61 => w_V_78_reload,
        din62 => w_V_79_reload,
        din63 => w_V_80_reload,
        din64 => tmp_4_fu_790_p65,
        dout => tmp_4_fu_790_p66);

    flow_control_loop_pipe_sequential_init_U : component sha256_acc_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    b_V_fu_244_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    b_V_fu_244 <= ap_const_lv32_6A09E667;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    b_V_fu_244 <= a_V_fu_1200_p2;
                end if;
            end if; 
        end if;
    end process;

    c_V_1_fu_232_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    c_V_1_fu_232 <= ap_const_lv32_BB67AE85;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    c_V_1_fu_232 <= a_V_2_reg_1326;
                end if;
            end if; 
        end if;
    end process;

    d_V_1_fu_256_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    d_V_1_fu_256 <= ap_const_lv32_3C6EF372;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    d_V_1_fu_256 <= c_V_1_fu_232;
                end if;
            end if; 
        end if;
    end process;

    d_V_fu_236_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    d_V_fu_236 <= ap_const_lv32_A54FF53A;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    d_V_fu_236 <= c_V_reg_1338;
                end if;
            end if; 
        end if;
    end process;

    f_V_fu_260_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    f_V_fu_260 <= ap_const_lv32_510E527F;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    f_V_fu_260 <= e_V_fu_1190_p2;
                end if;
            end if; 
        end if;
    end process;

    g_V_1_fu_240_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                g_V_1_fu_240 <= ap_const_lv32_9B05688C;
            elsif (((icmp_ln30_reg_1312 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                g_V_1_fu_240 <= f_V_fu_260;
            end if; 
        end if;
    end process;

    h_val_V_1_fu_264_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                h_val_V_1_fu_264 <= ap_const_lv32_1F83D9AB;
            elsif (((icmp_ln30_reg_1312 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                h_val_V_1_fu_264 <= g_V_1_fu_240;
            end if; 
        end if;
    end process;

    h_val_V_fu_248_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                h_val_V_fu_248 <= ap_const_lv32_5BE0CD19;
            elsif (((icmp_ln30_reg_1312 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                h_val_V_fu_248 <= h_val_V_1_fu_264;
            end if; 
        end if;
    end process;

    i_fu_252_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln30_fu_769_p2 = ap_const_lv1_0))) then 
                    i_fu_252 <= add_ln30_fu_775_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_252 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                a_V_2_reg_1326 <= b_V_fu_244;
                c_V_reg_1338 <= d_V_1_fu_256;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln30_reg_1312 <= icmp_ln30_fu_769_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln30_reg_1312 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                t1_V_reg_1345 <= t1_V_fu_1070_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln30_fu_769_p2 = ap_const_lv1_0))) then
                tmp_4_reg_1321 <= tmp_4_fu_790_p66;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to1, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to1 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    a_V_2_out <= b_V_fu_244;

    a_V_2_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage1, icmp_ln30_reg_1312, ap_block_pp0_stage1_11001)
    begin
        if (((icmp_ln30_reg_1312 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            a_V_2_out_ap_vld <= ap_const_logic_1;
        else 
            a_V_2_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    a_V_fu_1200_p2 <= std_logic_vector(unsigned(add_ln186_5_fu_1195_p2) + unsigned(ret_V_8_fu_1163_p2));
    add_ln186_1_fu_1059_p2 <= std_logic_vector(unsigned(ret_V_4_fu_1047_p2) + unsigned(tmp_4_reg_1321));
    add_ln186_2_fu_1064_p2 <= std_logic_vector(unsigned(add_ln186_1_fu_1059_p2) + unsigned(ret_V_fu_1023_p2));
    add_ln186_5_fu_1195_p2 <= std_logic_vector(unsigned(t1_V_reg_1345) + unsigned(ret_V_11_fu_1184_p2));
    add_ln186_fu_1053_p2 <= std_logic_vector(unsigned(k_V_q0) + unsigned(h_val_V_fu_248));
    add_ln30_fu_775_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_1) + unsigned(ap_const_lv7_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage1_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, icmp_ln30_reg_1312)
    begin
        if (((icmp_ln30_reg_1312 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to1_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_0)) then 
            ap_idle_pp0_1to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, i_fu_252)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_1 <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_i_1 <= i_fu_252;
        end if; 
    end process;

    b_V_out <= c_V_1_fu_232;

    b_V_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage1, icmp_ln30_reg_1312, ap_block_pp0_stage1_11001)
    begin
        if (((icmp_ln30_reg_1312 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            b_V_out_ap_vld <= ap_const_logic_1;
        else 
            b_V_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    c_V_out <= d_V_1_fu_256;

    c_V_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage1, icmp_ln30_reg_1312, ap_block_pp0_stage1_11001)
    begin
        if (((icmp_ln30_reg_1312 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            c_V_out_ap_vld <= ap_const_logic_1;
        else 
            c_V_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    d_V_out <= d_V_fu_236;

    d_V_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage1, icmp_ln30_reg_1312, ap_block_pp0_stage1_11001)
    begin
        if (((icmp_ln30_reg_1312 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            d_V_out_ap_vld <= ap_const_logic_1;
        else 
            d_V_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    e_V_2_out <= f_V_fu_260;

    e_V_2_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage1, icmp_ln30_reg_1312, ap_block_pp0_stage1_11001)
    begin
        if (((icmp_ln30_reg_1312 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            e_V_2_out_ap_vld <= ap_const_logic_1;
        else 
            e_V_2_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    e_V_fu_1190_p2 <= std_logic_vector(unsigned(t1_V_reg_1345) + unsigned(d_V_fu_236));
    f_V_out <= g_V_1_fu_240;

    f_V_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage1, icmp_ln30_reg_1312, ap_block_pp0_stage1_11001)
    begin
        if (((icmp_ln30_reg_1312 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            f_V_out_ap_vld <= ap_const_logic_1;
        else 
            f_V_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    g_V_out <= h_val_V_1_fu_264;

    g_V_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage1, icmp_ln30_reg_1312, ap_block_pp0_stage1_11001)
    begin
        if (((icmp_ln30_reg_1312 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            g_V_out_ap_vld <= ap_const_logic_1;
        else 
            g_V_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    h_val_V_out <= h_val_V_fu_248;

    h_val_V_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage1, icmp_ln30_reg_1312, ap_block_pp0_stage1_11001)
    begin
        if (((icmp_ln30_reg_1312 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            h_val_V_out_ap_vld <= ap_const_logic_1;
        else 
            h_val_V_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln30_fu_769_p2 <= "1" when (ap_sig_allocacmp_i_1 = ap_const_lv7_40) else "0";
    k_V_address0 <= zext_ln30_fu_781_p1(6 - 1 downto 0);

    k_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            k_V_ce0 <= ap_const_logic_1;
        else 
            k_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    r_V_5_fu_951_p4 <= f_V_fu_260(31 downto 6);
    r_V_6_fu_973_p4 <= f_V_fu_260(31 downto 11);
    r_V_7_fu_995_p4 <= f_V_fu_260(31 downto 25);
    r_V_8_fu_1097_p4 <= a_V_2_reg_1326(31 downto 2);
    r_V_9_fu_1117_p4 <= a_V_2_reg_1326(31 downto 13);
    r_V_fu_1035_p2 <= (f_V_fu_260 xor ap_const_lv32_FFFFFFFF);
    r_V_s_fu_1137_p4 <= a_V_2_reg_1326(31 downto 22);
    ret_V_11_fu_1184_p2 <= (ret_V_21_fu_1179_p2 xor ret_V_20_fu_1174_p2);
    ret_V_12_fu_965_p3 <= (trunc_ln1669_fu_961_p1 & r_V_5_fu_951_p4);
    ret_V_13_fu_987_p3 <= (trunc_ln1669_1_fu_983_p1 & r_V_6_fu_973_p4);
    ret_V_14_fu_1009_p3 <= (trunc_ln1669_2_fu_1005_p1 & r_V_7_fu_995_p4);
    ret_V_15_fu_1029_p2 <= (g_V_1_fu_240 and f_V_fu_260);
    ret_V_16_fu_1041_p2 <= (r_V_fu_1035_p2 and h_val_V_1_fu_264);
    ret_V_17_fu_1109_p3 <= (trunc_ln1669_3_fu_1106_p1 & r_V_8_fu_1097_p4);
    ret_V_18_fu_1129_p3 <= (trunc_ln1669_4_fu_1126_p1 & r_V_9_fu_1117_p4);
    ret_V_19_fu_1149_p3 <= (trunc_ln1669_5_fu_1146_p1 & r_V_s_fu_1137_p4);
    ret_V_20_fu_1174_p2 <= (xor_ln1499_5_fu_1169_p2 and a_V_2_reg_1326);
    ret_V_21_fu_1179_p2 <= (c_V_reg_1338 and c_V_1_fu_232);
    ret_V_4_fu_1047_p2 <= (ret_V_16_fu_1041_p2 xor ret_V_15_fu_1029_p2);
    ret_V_8_fu_1163_p2 <= (xor_ln1499_3_fu_1157_p2 xor ret_V_19_fu_1149_p3);
    ret_V_fu_1023_p2 <= (xor_ln1499_fu_1017_p2 xor ret_V_14_fu_1009_p3);
    t1_V_fu_1070_p2 <= std_logic_vector(unsigned(add_ln186_2_fu_1064_p2) + unsigned(add_ln186_fu_1053_p2));
    tmp_4_fu_790_p65 <= ap_sig_allocacmp_i_1(6 - 1 downto 0);
    trunc_ln1669_1_fu_983_p1 <= f_V_fu_260(11 - 1 downto 0);
    trunc_ln1669_2_fu_1005_p1 <= f_V_fu_260(25 - 1 downto 0);
    trunc_ln1669_3_fu_1106_p1 <= a_V_2_reg_1326(2 - 1 downto 0);
    trunc_ln1669_4_fu_1126_p1 <= a_V_2_reg_1326(13 - 1 downto 0);
    trunc_ln1669_5_fu_1146_p1 <= a_V_2_reg_1326(22 - 1 downto 0);
    trunc_ln1669_fu_961_p1 <= f_V_fu_260(6 - 1 downto 0);
    xor_ln1499_3_fu_1157_p2 <= (ret_V_18_fu_1129_p3 xor ret_V_17_fu_1109_p3);
    xor_ln1499_5_fu_1169_p2 <= (c_V_reg_1338 xor c_V_1_fu_232);
    xor_ln1499_fu_1017_p2 <= (ret_V_13_fu_987_p3 xor ret_V_12_fu_965_p3);
    zext_ln30_fu_781_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i_1),64));
end behav;
